// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: protocgen/descriptor/openapiconfig/openapiconfig.proto

package openapiconfig

import (
	options "github.com/kamalyes/grpc-runtime/protocgen/openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OpenAPI 文件级配置 | [EN] OpenAPI file-level option binding
type OpenAPIFileOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// proto 文件路径 | [EN] Proto file path
	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// 文件级 OpenAPI 选项 | [EN] File-level OpenAPI option
	Option        *options.Swagger `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIFileOption) Reset() {
	*x = OpenAPIFileOption{}
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIFileOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIFileOption) ProtoMessage() {}

func (x *OpenAPIFileOption) ProtoReflect() protoreflect.Message {
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIFileOption.ProtoReflect.Descriptor instead.
func (*OpenAPIFileOption) Descriptor() ([]byte, []int) {
	return file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescGZIP(), []int{0}
}

func (x *OpenAPIFileOption) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *OpenAPIFileOption) GetOption() *options.Swagger {
	if x != nil {
		return x.Option
	}
	return nil
}

// OpenAPI 方法级配置 | [EN] OpenAPI method-level option binding
type OpenAPIMethodOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 完整方法名 | [EN] Fully-qualified method name
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// 方法级 OpenAPI 选项 | [EN] Method-level OpenAPI option
	Option        *options.Operation `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIMethodOption) Reset() {
	*x = OpenAPIMethodOption{}
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIMethodOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIMethodOption) ProtoMessage() {}

func (x *OpenAPIMethodOption) ProtoReflect() protoreflect.Message {
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIMethodOption.ProtoReflect.Descriptor instead.
func (*OpenAPIMethodOption) Descriptor() ([]byte, []int) {
	return file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescGZIP(), []int{1}
}

func (x *OpenAPIMethodOption) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OpenAPIMethodOption) GetOption() *options.Operation {
	if x != nil {
		return x.Option
	}
	return nil
}

// OpenAPI 消息级配置 | [EN] OpenAPI message-level option binding
type OpenAPIMessageOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 完整消息名 | [EN] Fully-qualified message name
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// 消息级 OpenAPI 选项 | [EN] Message-level OpenAPI option
	Option        *options.Schema `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIMessageOption) Reset() {
	*x = OpenAPIMessageOption{}
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIMessageOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIMessageOption) ProtoMessage() {}

func (x *OpenAPIMessageOption) ProtoReflect() protoreflect.Message {
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIMessageOption.ProtoReflect.Descriptor instead.
func (*OpenAPIMessageOption) Descriptor() ([]byte, []int) {
	return file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescGZIP(), []int{2}
}

func (x *OpenAPIMessageOption) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OpenAPIMessageOption) GetOption() *options.Schema {
	if x != nil {
		return x.Option
	}
	return nil
}

// OpenAPI 服务级配置 | [EN] OpenAPI service-level option binding
type OpenAPIServiceOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 完整服务名 | [EN] Fully-qualified service name
	Service string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// 服务级 OpenAPI 标签选项 | [EN] Service-level OpenAPI tag option
	Option        *options.Tag `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIServiceOption) Reset() {
	*x = OpenAPIServiceOption{}
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIServiceOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIServiceOption) ProtoMessage() {}

func (x *OpenAPIServiceOption) ProtoReflect() protoreflect.Message {
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIServiceOption.ProtoReflect.Descriptor instead.
func (*OpenAPIServiceOption) Descriptor() ([]byte, []int) {
	return file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescGZIP(), []int{3}
}

func (x *OpenAPIServiceOption) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *OpenAPIServiceOption) GetOption() *options.Tag {
	if x != nil {
		return x.Option
	}
	return nil
}

// OpenAPI 字段级配置 | [EN] OpenAPI field-level option binding
type OpenAPIFieldOption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 完整字段名 | [EN] Fully-qualified field name
	Field string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// 字段级 OpenAPI 选项 | [EN] Field-level OpenAPI option
	Option        *options.JSONSchema `protobuf:"bytes,2,opt,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIFieldOption) Reset() {
	*x = OpenAPIFieldOption{}
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIFieldOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIFieldOption) ProtoMessage() {}

func (x *OpenAPIFieldOption) ProtoReflect() protoreflect.Message {
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIFieldOption.ProtoReflect.Descriptor instead.
func (*OpenAPIFieldOption) Descriptor() ([]byte, []int) {
	return file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescGZIP(), []int{4}
}

func (x *OpenAPIFieldOption) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OpenAPIFieldOption) GetOption() *options.JSONSchema {
	if x != nil {
		return x.Option
	}
	return nil
}

// OpenAPI 配置集合 | [EN] OpenAPI option binding collection
type OpenAPIOptions struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	File          []*OpenAPIFileOption    `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	Method        []*OpenAPIMethodOption  `protobuf:"bytes,2,rep,name=method,proto3" json:"method,omitempty"`
	Message       []*OpenAPIMessageOption `protobuf:"bytes,3,rep,name=message,proto3" json:"message,omitempty"`
	Service       []*OpenAPIServiceOption `protobuf:"bytes,4,rep,name=service,proto3" json:"service,omitempty"`
	Field         []*OpenAPIFieldOption   `protobuf:"bytes,5,rep,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAPIOptions) Reset() {
	*x = OpenAPIOptions{}
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIOptions) ProtoMessage() {}

func (x *OpenAPIOptions) ProtoReflect() protoreflect.Message {
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIOptions.ProtoReflect.Descriptor instead.
func (*OpenAPIOptions) Descriptor() ([]byte, []int) {
	return file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescGZIP(), []int{5}
}

func (x *OpenAPIOptions) GetFile() []*OpenAPIFileOption {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *OpenAPIOptions) GetMethod() []*OpenAPIMethodOption {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *OpenAPIOptions) GetMessage() []*OpenAPIMessageOption {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *OpenAPIOptions) GetService() []*OpenAPIServiceOption {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *OpenAPIOptions) GetField() []*OpenAPIFieldOption {
	if x != nil {
		return x.Field
	}
	return nil
}

// OpenAPI 配置文件根节点 | [EN] Root node for OpenAPI configuration files
type OpenAPIConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenAPI 选项集合 | [EN] OpenAPI option collection
	OpenapiOptions *OpenAPIOptions `protobuf:"bytes,1,opt,name=openapi_options,json=openapiOptions,proto3" json:"openapi_options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpenAPIConfig) Reset() {
	*x = OpenAPIConfig{}
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAPIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAPIConfig) ProtoMessage() {}

func (x *OpenAPIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAPIConfig.ProtoReflect.Descriptor instead.
func (*OpenAPIConfig) Descriptor() ([]byte, []int) {
	return file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescGZIP(), []int{6}
}

func (x *OpenAPIConfig) GetOpenapiOptions() *OpenAPIOptions {
	if x != nil {
		return x.OpenapiOptions
	}
	return nil
}

var File_protocgen_descriptor_openapiconfig_openapiconfig_proto protoreflect.FileDescriptor

const file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDesc = "" +
	"\n" +
	"6protocgen/descriptor/openapiconfig/openapiconfig.proto\x12/grpc.runtime.protocgen.descriptor.openapiconfig\x1a+protocgen/openapiv2/options/openapiv2.proto\"s\n" +
	"\x11OpenAPIFileOption\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12J\n" +
	"\x06option\x18\x02 \x01(\v22.grpc.runtime.protoc_gen_openapiv2.options.SwaggerR\x06option\"{\n" +
	"\x13OpenAPIMethodOption\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12L\n" +
	"\x06option\x18\x02 \x01(\v24.grpc.runtime.protoc_gen_openapiv2.options.OperationR\x06option\"{\n" +
	"\x14OpenAPIMessageOption\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12I\n" +
	"\x06option\x18\x02 \x01(\v21.grpc.runtime.protoc_gen_openapiv2.options.SchemaR\x06option\"x\n" +
	"\x14OpenAPIServiceOption\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12F\n" +
	"\x06option\x18\x02 \x01(\v2..grpc.runtime.protoc_gen_openapiv2.options.TagR\x06option\"y\n" +
	"\x12OpenAPIFieldOption\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12M\n" +
	"\x06option\x18\x02 \x01(\v25.grpc.runtime.protoc_gen_openapiv2.options.JSONSchemaR\x06option\"\xe3\x03\n" +
	"\x0eOpenAPIOptions\x12V\n" +
	"\x04file\x18\x01 \x03(\v2B.grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIFileOptionR\x04file\x12\\\n" +
	"\x06method\x18\x02 \x03(\v2D.grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIMethodOptionR\x06method\x12_\n" +
	"\amessage\x18\x03 \x03(\v2E.grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIMessageOptionR\amessage\x12_\n" +
	"\aservice\x18\x04 \x03(\v2E.grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIServiceOptionR\aservice\x12Y\n" +
	"\x05field\x18\x05 \x03(\v2C.grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIFieldOptionR\x05field\"y\n" +
	"\rOpenAPIConfig\x12h\n" +
	"\x0fopenapi_options\x18\x01 \x01(\v2?.grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIOptionsR\x0eopenapiOptionsBEZCgithub.com/kamalyes/grpc-runtime/protocgen/descriptor/openapiconfigb\x06proto3"

var (
	file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescOnce sync.Once
	file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescData []byte
)

func file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescGZIP() []byte {
	file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescOnce.Do(func() {
		file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDesc), len(file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDesc)))
	})
	return file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDescData
}

var file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protocgen_descriptor_openapiconfig_openapiconfig_proto_goTypes = []any{
	(*OpenAPIFileOption)(nil),    // 0: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIFileOption
	(*OpenAPIMethodOption)(nil),  // 1: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIMethodOption
	(*OpenAPIMessageOption)(nil), // 2: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIMessageOption
	(*OpenAPIServiceOption)(nil), // 3: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIServiceOption
	(*OpenAPIFieldOption)(nil),   // 4: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIFieldOption
	(*OpenAPIOptions)(nil),       // 5: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIOptions
	(*OpenAPIConfig)(nil),        // 6: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIConfig
	(*options.Swagger)(nil),      // 7: grpc.runtime.protoc_gen_openapiv2.options.Swagger
	(*options.Operation)(nil),    // 8: grpc.runtime.protoc_gen_openapiv2.options.Operation
	(*options.Schema)(nil),       // 9: grpc.runtime.protoc_gen_openapiv2.options.Schema
	(*options.Tag)(nil),          // 10: grpc.runtime.protoc_gen_openapiv2.options.Tag
	(*options.JSONSchema)(nil),   // 11: grpc.runtime.protoc_gen_openapiv2.options.JSONSchema
}
var file_protocgen_descriptor_openapiconfig_openapiconfig_proto_depIdxs = []int32{
	7,  // 0: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIFileOption.option:type_name -> grpc.runtime.protoc_gen_openapiv2.options.Swagger
	8,  // 1: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIMethodOption.option:type_name -> grpc.runtime.protoc_gen_openapiv2.options.Operation
	9,  // 2: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIMessageOption.option:type_name -> grpc.runtime.protoc_gen_openapiv2.options.Schema
	10, // 3: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIServiceOption.option:type_name -> grpc.runtime.protoc_gen_openapiv2.options.Tag
	11, // 4: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIFieldOption.option:type_name -> grpc.runtime.protoc_gen_openapiv2.options.JSONSchema
	0,  // 5: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIOptions.file:type_name -> grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIFileOption
	1,  // 6: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIOptions.method:type_name -> grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIMethodOption
	2,  // 7: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIOptions.message:type_name -> grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIMessageOption
	3,  // 8: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIOptions.service:type_name -> grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIServiceOption
	4,  // 9: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIOptions.field:type_name -> grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIFieldOption
	5,  // 10: grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIConfig.openapi_options:type_name -> grpc.runtime.protocgen.descriptor.openapiconfig.OpenAPIOptions
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protocgen_descriptor_openapiconfig_openapiconfig_proto_init() }
func file_protocgen_descriptor_openapiconfig_openapiconfig_proto_init() {
	if File_protocgen_descriptor_openapiconfig_openapiconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDesc), len(file_protocgen_descriptor_openapiconfig_openapiconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocgen_descriptor_openapiconfig_openapiconfig_proto_goTypes,
		DependencyIndexes: file_protocgen_descriptor_openapiconfig_openapiconfig_proto_depIdxs,
		MessageInfos:      file_protocgen_descriptor_openapiconfig_openapiconfig_proto_msgTypes,
	}.Build()
	File_protocgen_descriptor_openapiconfig_openapiconfig_proto = out.File
	file_protocgen_descriptor_openapiconfig_openapiconfig_proto_goTypes = nil
	file_protocgen_descriptor_openapiconfig_openapiconfig_proto_depIdxs = nil
}
