// 示例消息与服务定义 | [EN] Example messages and service definitions.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: testpb/example.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NumericEnum 数值枚举类型 | [EN] Numeric enum type.
type NumericEnum int32

const (
	// ZERO 零 | [EN] Zero value.
	NumericEnum_ZERO NumericEnum = 0
	// ONE 一 | [EN] One value.
	NumericEnum_ONE NumericEnum = 1
)

// Enum value maps for NumericEnum.
var (
	NumericEnum_name = map[int32]string{
		0: "ZERO",
		1: "ONE",
	}
	NumericEnum_value = map[string]int32{
		"ZERO": 0,
		"ONE":  1,
	}
)

func (x NumericEnum) Enum() *NumericEnum {
	p := new(NumericEnum)
	*p = x
	return p
}

func (x NumericEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumericEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_testpb_example_proto_enumTypes[0].Descriptor()
}

func (NumericEnum) Type() protoreflect.EnumType {
	return &file_testpb_example_proto_enumTypes[0]
}

func (x NumericEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumericEnum.Descriptor instead.
func (NumericEnum) EnumDescriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{0}
}

// DeepEnum 深层枚举 | [EN] Deep nested enum.
type ABitOfEverything_Nested_DeepEnum int32

const (
	// FALSE 假 | [EN] False value.
	ABitOfEverything_Nested_FALSE ABitOfEverything_Nested_DeepEnum = 0
	// TRUE 真 | [EN] True value.
	ABitOfEverything_Nested_TRUE ABitOfEverything_Nested_DeepEnum = 1
)

// Enum value maps for ABitOfEverything_Nested_DeepEnum.
var (
	ABitOfEverything_Nested_DeepEnum_name = map[int32]string{
		0: "FALSE",
		1: "TRUE",
	}
	ABitOfEverything_Nested_DeepEnum_value = map[string]int32{
		"FALSE": 0,
		"TRUE":  1,
	}
)

func (x ABitOfEverything_Nested_DeepEnum) Enum() *ABitOfEverything_Nested_DeepEnum {
	p := new(ABitOfEverything_Nested_DeepEnum)
	*p = x
	return p
}

func (x ABitOfEverything_Nested_DeepEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ABitOfEverything_Nested_DeepEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_testpb_example_proto_enumTypes[1].Descriptor()
}

func (ABitOfEverything_Nested_DeepEnum) Type() protoreflect.EnumType {
	return &file_testpb_example_proto_enumTypes[1]
}

func (x ABitOfEverything_Nested_DeepEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ABitOfEverything_Nested_DeepEnum.Descriptor instead.
func (ABitOfEverything_Nested_DeepEnum) EnumDescriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{1, 0, 0}
}

// ResponseType 响应类型枚举 | [EN] Response type enum.
type RepeatedResponseBodyOut_Response_ResponseType int32

const (
	// UNKNOWN 未知类型 | [EN] Unknown type.
	RepeatedResponseBodyOut_Response_UNKNOWN RepeatedResponseBodyOut_Response_ResponseType = 0
	// A 类型 A | [EN] Type A.
	RepeatedResponseBodyOut_Response_A RepeatedResponseBodyOut_Response_ResponseType = 1
	// B 类型 B | [EN] Type B.
	RepeatedResponseBodyOut_Response_B RepeatedResponseBodyOut_Response_ResponseType = 2
)

// Enum value maps for RepeatedResponseBodyOut_Response_ResponseType.
var (
	RepeatedResponseBodyOut_Response_ResponseType_name = map[int32]string{
		0: "UNKNOWN",
		1: "A",
		2: "B",
	}
	RepeatedResponseBodyOut_Response_ResponseType_value = map[string]int32{
		"UNKNOWN": 0,
		"A":       1,
		"B":       2,
	}
)

func (x RepeatedResponseBodyOut_Response_ResponseType) Enum() *RepeatedResponseBodyOut_Response_ResponseType {
	p := new(RepeatedResponseBodyOut_Response_ResponseType)
	*p = x
	return p
}

func (x RepeatedResponseBodyOut_Response_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepeatedResponseBodyOut_Response_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_testpb_example_proto_enumTypes[2].Descriptor()
}

func (RepeatedResponseBodyOut_Response_ResponseType) Type() protoreflect.EnumType {
	return &file_testpb_example_proto_enumTypes[2]
}

func (x RepeatedResponseBodyOut_Response_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepeatedResponseBodyOut_Response_ResponseType.Descriptor instead.
func (RepeatedResponseBodyOut_Response_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{3, 0, 0}
}

// SimpleMessage 简单消息，仅包含一个 id 字段 | [EN] Simple message with only an id field.
type SimpleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 消息唯一标识 | [EN] Message identifier.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_testpb_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ABitOfEverything 综合测试消息，覆盖常用 proto3 字段类型 | [EN] Message covering common proto3 field types.
type ABitOfEverything struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// single_nested 单个嵌套消息 | [EN] Single nested message.
	SingleNested *ABitOfEverything_Nested `protobuf:"bytes,25,opt,name=single_nested,json=singleNested,proto3" json:"single_nested,omitempty"`
	// uuid 通用唯一标识 | [EN] Unique identifier.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// nested 嵌套消息列表 | [EN] Nested message list.
	Nested []*ABitOfEverything_Nested `protobuf:"bytes,2,rep,name=nested,proto3" json:"nested,omitempty"`
	// float_value 浮点数 | [EN] Float value.
	FloatValue float32 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	// double_value 双精度浮点数 | [EN] Double value.
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	// int64_value 64 位整数 | [EN] int64 value.
	Int64Value int64 `protobuf:"varint,5,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	// uint64_value 无符号 64 位整数 | [EN] uint64 value.
	Uint64Value uint64 `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	// int32_value 32 位整数 | [EN] int32 value.
	Int32Value int32 `protobuf:"varint,7,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	// fixed64_value 固定 64 位值 | [EN] fixed64 value.
	Fixed64Value uint64 `protobuf:"fixed64,8,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	// fixed32_value 固定 32 位值 | [EN] fixed32 value.
	Fixed32Value uint32 `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	// bool_value 布尔值 | [EN] Boolean value.
	BoolValue bool `protobuf:"varint,10,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	// string_value 字符串 | [EN] String value.
	StringValue string `protobuf:"bytes,11,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	// bytes_value 字节数组 | [EN] Bytes value.
	BytesValue []byte `protobuf:"bytes,29,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	// uint32_value 无符号 32 位整数 | [EN] uint32 value.
	Uint32Value uint32 `protobuf:"varint,13,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	// enum_value 枚举值 | [EN] Enum value.
	EnumValue NumericEnum `protobuf:"varint,14,opt,name=enum_value,json=enumValue,proto3,enum=grpc.runtime.testpb.NumericEnum" json:"enum_value,omitempty"`
	// sfixed32_value 有符号固定 32 位值 | [EN] sfixed32 value.
	Sfixed32Value int32 `protobuf:"fixed32,15,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	// sfixed64_value 有符号固定 64 位值 | [EN] sfixed64 value.
	Sfixed64Value int64 `protobuf:"fixed64,16,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	// sint32_value 有符号 32 位整数 | [EN] sint32 value.
	Sint32Value int32 `protobuf:"zigzag32,17,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	// sint64_value 有符号 64 位整数 | [EN] sint64 value.
	Sint64Value int64 `protobuf:"zigzag64,18,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	// repeated_string_value 字符串列表 | [EN] Repeated string value.
	RepeatedStringValue []string `protobuf:"bytes,19,rep,name=repeated_string_value,json=repeatedStringValue,proto3" json:"repeated_string_value,omitempty"`
	// oneof_value 单值选择 | [EN] Oneof value.
	//
	// Types that are valid to be assigned to OneofValue:
	//
	//	*ABitOfEverything_OneofEmpty
	//	*ABitOfEverything_OneofString
	OneofValue isABitOfEverything_OneofValue `protobuf_oneof:"oneof_value"`
	// map_value 枚举值映射 | [EN] Enum map value.
	MapValue map[string]NumericEnum `protobuf:"bytes,22,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=grpc.runtime.testpb.NumericEnum"`
	// mapped_string_value 字符串映射 | [EN] String map value.
	MappedStringValue map[string]string `protobuf:"bytes,23,rep,name=mapped_string_value,json=mappedStringValue,proto3" json:"mapped_string_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// mapped_nested_value 嵌套消息映射 | [EN] Nested message map value.
	MappedNestedValue map[string]*ABitOfEverything_Nested `protobuf:"bytes,24,rep,name=mapped_nested_value,json=mappedNestedValue,proto3" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// nonConventionalNameValue 非常规命名字段 | [EN] Non-conventional name value.
	NonConventionalNameValue string `protobuf:"bytes,26,opt,name=nonConventionalNameValue,proto3" json:"nonConventionalNameValue,omitempty"`
	// timestamp_value 时间戳 | [EN] Timestamp value.
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	// repeated_enum_value 枚举值列表 | [EN] Repeated enum values.
	RepeatedEnumValue []NumericEnum `protobuf:"varint,28,rep,packed,name=repeated_enum_value,json=repeatedEnumValue,proto3,enum=grpc.runtime.testpb.NumericEnum" json:"repeated_enum_value,omitempty"`
	// repeated_enum_annotation 带注释的枚举值列表 | [EN] Annotated repeated enum values.
	RepeatedEnumAnnotation []NumericEnum `protobuf:"varint,32,rep,packed,name=repeated_enum_annotation,json=repeatedEnumAnnotation,proto3,enum=grpc.runtime.testpb.NumericEnum" json:"repeated_enum_annotation,omitempty"`
	// enum_value_annotation 带注释的枚举值 | [EN] Annotated enum value.
	EnumValueAnnotation NumericEnum `protobuf:"varint,33,opt,name=enum_value_annotation,json=enumValueAnnotation,proto3,enum=grpc.runtime.testpb.NumericEnum" json:"enum_value_annotation,omitempty"`
	// repeated_string_annotation 带注释的字符串列表 | [EN] Annotated repeated string values.
	RepeatedStringAnnotation []string `protobuf:"bytes,34,rep,name=repeated_string_annotation,json=repeatedStringAnnotation,proto3" json:"repeated_string_annotation,omitempty"`
	// repeated_nested_annotation 带注释的嵌套消息列表 | [EN] Annotated repeated nested messages.
	RepeatedNestedAnnotation []*ABitOfEverything_Nested `protobuf:"bytes,35,rep,name=repeated_nested_annotation,json=repeatedNestedAnnotation,proto3" json:"repeated_nested_annotation,omitempty"`
	// nested_annotation 带注释的嵌套消息 | [EN] Annotated nested message.
	NestedAnnotation *ABitOfEverything_Nested `protobuf:"bytes,36,opt,name=nested_annotation,json=nestedAnnotation,proto3" json:"nested_annotation,omitempty"`
	// int64_override_type 类型覆盖测试字段 | [EN] Type override test field.
	Int64OverrideType int64 `protobuf:"varint,37,opt,name=int64_override_type,json=int64OverrideType,proto3" json:"int64_override_type,omitempty"`
	// anytype Any 类型字段 | [EN] Any field.
	Anytype *anypb.Any `protobuf:"bytes,38,opt,name=anytype,proto3" json:"anytype,omitempty"`
	// repeated_anytype Any 类型列表 | [EN] Repeated Any field.
	RepeatedAnytype []*anypb.Any `protobuf:"bytes,39,rep,name=repeated_anytype,json=repeatedAnytype,proto3" json:"repeated_anytype,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ABitOfEverything) Reset() {
	*x = ABitOfEverything{}
	mi := &file_testpb_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABitOfEverything) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABitOfEverything) ProtoMessage() {}

func (x *ABitOfEverything) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABitOfEverything.ProtoReflect.Descriptor instead.
func (*ABitOfEverything) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{1}
}

func (x *ABitOfEverything) GetSingleNested() *ABitOfEverything_Nested {
	if x != nil {
		return x.SingleNested
	}
	return nil
}

func (x *ABitOfEverything) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ABitOfEverything) GetNested() []*ABitOfEverything_Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *ABitOfEverything) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *ABitOfEverything) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *ABitOfEverything) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *ABitOfEverything) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *ABitOfEverything) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *ABitOfEverything) GetFixed64Value() uint64 {
	if x != nil {
		return x.Fixed64Value
	}
	return 0
}

func (x *ABitOfEverything) GetFixed32Value() uint32 {
	if x != nil {
		return x.Fixed32Value
	}
	return 0
}

func (x *ABitOfEverything) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *ABitOfEverything) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *ABitOfEverything) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *ABitOfEverything) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *ABitOfEverything) GetEnumValue() NumericEnum {
	if x != nil {
		return x.EnumValue
	}
	return NumericEnum_ZERO
}

func (x *ABitOfEverything) GetSfixed32Value() int32 {
	if x != nil {
		return x.Sfixed32Value
	}
	return 0
}

func (x *ABitOfEverything) GetSfixed64Value() int64 {
	if x != nil {
		return x.Sfixed64Value
	}
	return 0
}

func (x *ABitOfEverything) GetSint32Value() int32 {
	if x != nil {
		return x.Sint32Value
	}
	return 0
}

func (x *ABitOfEverything) GetSint64Value() int64 {
	if x != nil {
		return x.Sint64Value
	}
	return 0
}

func (x *ABitOfEverything) GetRepeatedStringValue() []string {
	if x != nil {
		return x.RepeatedStringValue
	}
	return nil
}

func (x *ABitOfEverything) GetOneofValue() isABitOfEverything_OneofValue {
	if x != nil {
		return x.OneofValue
	}
	return nil
}

func (x *ABitOfEverything) GetOneofEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.OneofValue.(*ABitOfEverything_OneofEmpty); ok {
			return x.OneofEmpty
		}
	}
	return nil
}

func (x *ABitOfEverything) GetOneofString() string {
	if x != nil {
		if x, ok := x.OneofValue.(*ABitOfEverything_OneofString); ok {
			return x.OneofString
		}
	}
	return ""
}

func (x *ABitOfEverything) GetMapValue() map[string]NumericEnum {
	if x != nil {
		return x.MapValue
	}
	return nil
}

func (x *ABitOfEverything) GetMappedStringValue() map[string]string {
	if x != nil {
		return x.MappedStringValue
	}
	return nil
}

func (x *ABitOfEverything) GetMappedNestedValue() map[string]*ABitOfEverything_Nested {
	if x != nil {
		return x.MappedNestedValue
	}
	return nil
}

func (x *ABitOfEverything) GetNonConventionalNameValue() string {
	if x != nil {
		return x.NonConventionalNameValue
	}
	return ""
}

func (x *ABitOfEverything) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampValue
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedEnumValue() []NumericEnum {
	if x != nil {
		return x.RepeatedEnumValue
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedEnumAnnotation() []NumericEnum {
	if x != nil {
		return x.RepeatedEnumAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetEnumValueAnnotation() NumericEnum {
	if x != nil {
		return x.EnumValueAnnotation
	}
	return NumericEnum_ZERO
}

func (x *ABitOfEverything) GetRepeatedStringAnnotation() []string {
	if x != nil {
		return x.RepeatedStringAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedNestedAnnotation() []*ABitOfEverything_Nested {
	if x != nil {
		return x.RepeatedNestedAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetNestedAnnotation() *ABitOfEverything_Nested {
	if x != nil {
		return x.NestedAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetInt64OverrideType() int64 {
	if x != nil {
		return x.Int64OverrideType
	}
	return 0
}

func (x *ABitOfEverything) GetAnytype() *anypb.Any {
	if x != nil {
		return x.Anytype
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedAnytype() []*anypb.Any {
	if x != nil {
		return x.RepeatedAnytype
	}
	return nil
}

type isABitOfEverything_OneofValue interface {
	isABitOfEverything_OneofValue()
}

type ABitOfEverything_OneofEmpty struct {
	// oneof_empty 空值选项 | [EN] Empty oneof option.
	OneofEmpty *emptypb.Empty `protobuf:"bytes,20,opt,name=oneof_empty,json=oneofEmpty,proto3,oneof"`
}

type ABitOfEverything_OneofString struct {
	// oneof_string 字符串选项 | [EN] String oneof option.
	OneofString string `protobuf:"bytes,21,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

func (*ABitOfEverything_OneofEmpty) isABitOfEverything_OneofValue() {}

func (*ABitOfEverything_OneofString) isABitOfEverything_OneofValue() {}

// ResponseBodyOut 响应体外层消息 | [EN] Response body wrapper.
type ResponseBodyOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// response 响应消息 | [EN] Response message.
	Response      *ResponseBodyOut_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBodyOut) Reset() {
	*x = ResponseBodyOut{}
	mi := &file_testpb_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBodyOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBodyOut) ProtoMessage() {}

func (x *ResponseBodyOut) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBodyOut.ProtoReflect.Descriptor instead.
func (*ResponseBodyOut) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseBodyOut) GetResponse() *ResponseBodyOut_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// RepeatedResponseBodyOut 重复响应体外层消息 | [EN] Repeated response body wrapper.
type RepeatedResponseBodyOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// response 响应消息列表 | [EN] Response message list.
	Response      []*RepeatedResponseBodyOut_Response `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedResponseBodyOut) Reset() {
	*x = RepeatedResponseBodyOut{}
	mi := &file_testpb_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedResponseBodyOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedResponseBodyOut) ProtoMessage() {}

func (x *RepeatedResponseBodyOut) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedResponseBodyOut.ProtoReflect.Descriptor instead.
func (*RepeatedResponseBodyOut) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatedResponseBodyOut) GetResponse() []*RepeatedResponseBodyOut_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

// UpdateMessage 支持 FieldMask 局部更新的消息 | [EN] Message supporting FieldMask partial updates.
type UpdateMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// update_mask 更新字段掩码 | [EN] Update field mask.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// a_bit_of_everything 待更新的综合消息 | [EN] Message to update.
	ABitOfEverything *ABitOfEverything `protobuf:"bytes,2,opt,name=a_bit_of_everything,json=aBitOfEverything,proto3" json:"a_bit_of_everything,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateMessage) Reset() {
	*x = UpdateMessage{}
	mi := &file_testpb_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessage) ProtoMessage() {}

func (x *UpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessage.ProtoReflect.Descriptor instead.
func (*UpdateMessage) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateMessage) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateMessage) GetABitOfEverything() *ABitOfEverything {
	if x != nil {
		return x.ABitOfEverything
	}
	return nil
}

// NestedOuter 三层嵌套消息的外层 | [EN] Outer layer of a three-level nested message.
type NestedOuter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// one 第一层嵌套 | [EN] First nested layer.
	One           *NestedOne `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedOuter) Reset() {
	*x = NestedOuter{}
	mi := &file_testpb_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOuter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOuter) ProtoMessage() {}

func (x *NestedOuter) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedOuter.ProtoReflect.Descriptor instead.
func (*NestedOuter) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{5}
}

func (x *NestedOuter) GetOne() *NestedOne {
	if x != nil {
		return x.One
	}
	return nil
}

// NestedOne 三层嵌套消息的中间层 | [EN] Middle layer of a three-level nested message.
type NestedOne struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// two 第二层嵌套 | [EN] Second nested layer.
	Two           *NestedTwo `protobuf:"bytes,1,opt,name=two,proto3" json:"two,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedOne) Reset() {
	*x = NestedOne{}
	mi := &file_testpb_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedOne) ProtoMessage() {}

func (x *NestedOne) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedOne.ProtoReflect.Descriptor instead.
func (*NestedOne) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{6}
}

func (x *NestedOne) GetTwo() *NestedTwo {
	if x != nil {
		return x.Two
	}
	return nil
}

// NestedTwo 三层嵌套消息的内层 | [EN] Inner layer of a three-level nested message.
type NestedTwo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// three 第三层嵌套 | [EN] Third nested layer.
	Three         *NestedThree `protobuf:"bytes,1,opt,name=three,proto3" json:"three,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedTwo) Reset() {
	*x = NestedTwo{}
	mi := &file_testpb_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedTwo) ProtoMessage() {}

func (x *NestedTwo) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedTwo.ProtoReflect.Descriptor instead.
func (*NestedTwo) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{7}
}

func (x *NestedTwo) GetThree() *NestedThree {
	if x != nil {
		return x.Three
	}
	return nil
}

// NestedThree 三层嵌套消息的最内层 | [EN] Innermost layer of a three-level nested message.
type NestedThree struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// a 布尔字段 a | [EN] Boolean field a.
	A bool `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	// b 布尔字段 b | [EN] Boolean field b.
	B             bool `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedThree) Reset() {
	*x = NestedThree{}
	mi := &file_testpb_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedThree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedThree) ProtoMessage() {}

func (x *NestedThree) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedThree.ProtoReflect.Descriptor instead.
func (*NestedThree) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{8}
}

func (x *NestedThree) GetA() bool {
	if x != nil {
		return x.A
	}
	return false
}

func (x *NestedThree) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

// UpdateNestedRequest 嵌套消息更新请求 | [EN] Nested message update request.
type UpdateNestedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nested 嵌套消息 | [EN] Nested message.
	Nested *NestedOuter `protobuf:"bytes,1,opt,name=nested,proto3" json:"nested,omitempty"`
	// update_mask 更新字段掩码 | [EN] Update field mask.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNestedRequest) Reset() {
	*x = UpdateNestedRequest{}
	mi := &file_testpb_example_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNestedRequest) ProtoMessage() {}

func (x *UpdateNestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNestedRequest.ProtoReflect.Descriptor instead.
func (*UpdateNestedRequest) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateNestedRequest) GetNested() *NestedOuter {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *UpdateNestedRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Nested 嵌套消息类型 | [EN] Nested message type.
type ABitOfEverything_Nested struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name 嵌套字段名称 | [EN] Nested field name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// amount 数量 | [EN] Amount.
	Amount uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// ok 深层枚举值 | [EN] Deep enum value.
	Ok            ABitOfEverything_Nested_DeepEnum `protobuf:"varint,3,opt,name=ok,proto3,enum=grpc.runtime.testpb.ABitOfEverything_Nested_DeepEnum" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ABitOfEverything_Nested) Reset() {
	*x = ABitOfEverything_Nested{}
	mi := &file_testpb_example_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABitOfEverything_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABitOfEverything_Nested) ProtoMessage() {}

func (x *ABitOfEverything_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABitOfEverything_Nested.ProtoReflect.Descriptor instead.
func (*ABitOfEverything_Nested) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ABitOfEverything_Nested) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ABitOfEverything_Nested) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ABitOfEverything_Nested) GetOk() ABitOfEverything_Nested_DeepEnum {
	if x != nil {
		return x.Ok
	}
	return ABitOfEverything_Nested_FALSE
}

// Response 响应数据 | [EN] Response payload.
type ResponseBodyOut_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data 响应数据内容 | [EN] Response data.
	Data          string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBodyOut_Response) Reset() {
	*x = ResponseBodyOut_Response{}
	mi := &file_testpb_example_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBodyOut_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBodyOut_Response) ProtoMessage() {}

func (x *ResponseBodyOut_Response) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBodyOut_Response.ProtoReflect.Descriptor instead.
func (*ResponseBodyOut_Response) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ResponseBodyOut_Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Response 响应数据 | [EN] Response payload.
type RepeatedResponseBodyOut_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data 响应数据内容 | [EN] Response data.
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// type 响应类型 | [EN] Response type.
	Type          RepeatedResponseBodyOut_Response_ResponseType `protobuf:"varint,3,opt,name=type,proto3,enum=grpc.runtime.testpb.RepeatedResponseBodyOut_Response_ResponseType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedResponseBodyOut_Response) Reset() {
	*x = RepeatedResponseBodyOut_Response{}
	mi := &file_testpb_example_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedResponseBodyOut_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedResponseBodyOut_Response) ProtoMessage() {}

func (x *RepeatedResponseBodyOut_Response) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_example_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedResponseBodyOut_Response.ProtoReflect.Descriptor instead.
func (*RepeatedResponseBodyOut_Response) Descriptor() ([]byte, []int) {
	return file_testpb_example_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RepeatedResponseBodyOut_Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RepeatedResponseBodyOut_Response) GetType() RepeatedResponseBodyOut_Response_ResponseType {
	if x != nil {
		return x.Type
	}
	return RepeatedResponseBodyOut_Response_UNKNOWN
}

var File_testpb_example_proto protoreflect.FileDescriptor

const file_testpb_example_proto_rawDesc = "" +
	"\n" +
	"\x14testpb/example.proto\x12\x13grpc.runtime.testpb\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1f\n" +
	"\rSimpleMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc1\x13\n" +
	"\x10ABitOfEverything\x12Q\n" +
	"\rsingle_nested\x18\x19 \x01(\v2,.grpc.runtime.testpb.ABitOfEverything.NestedR\fsingleNested\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12D\n" +
	"\x06nested\x18\x02 \x03(\v2,.grpc.runtime.testpb.ABitOfEverything.NestedR\x06nested\x12\x1f\n" +
	"\vfloat_value\x18\x03 \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\x04 \x01(\x01R\vdoubleValue\x12\x1f\n" +
	"\vint64_value\x18\x05 \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fuint64_value\x18\x06 \x01(\x04R\vuint64Value\x12\x1f\n" +
	"\vint32_value\x18\a \x01(\x05R\n" +
	"int32Value\x12#\n" +
	"\rfixed64_value\x18\b \x01(\x06R\ffixed64Value\x12#\n" +
	"\rfixed32_value\x18\t \x01(\aR\ffixed32Value\x12\x1d\n" +
	"\n" +
	"bool_value\x18\n" +
	" \x01(\bR\tboolValue\x12!\n" +
	"\fstring_value\x18\v \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\x1d \x01(\fR\n" +
	"bytesValue\x12!\n" +
	"\fuint32_value\x18\r \x01(\rR\vuint32Value\x12?\n" +
	"\n" +
	"enum_value\x18\x0e \x01(\x0e2 .grpc.runtime.testpb.NumericEnumR\tenumValue\x12%\n" +
	"\x0esfixed32_value\x18\x0f \x01(\x0fR\rsfixed32Value\x12%\n" +
	"\x0esfixed64_value\x18\x10 \x01(\x10R\rsfixed64Value\x12!\n" +
	"\fsint32_value\x18\x11 \x01(\x11R\vsint32Value\x12!\n" +
	"\fsint64_value\x18\x12 \x01(\x12R\vsint64Value\x122\n" +
	"\x15repeated_string_value\x18\x13 \x03(\tR\x13repeatedStringValue\x129\n" +
	"\voneof_empty\x18\x14 \x01(\v2\x16.google.protobuf.EmptyH\x00R\n" +
	"oneofEmpty\x12#\n" +
	"\foneof_string\x18\x15 \x01(\tH\x00R\voneofString\x12P\n" +
	"\tmap_value\x18\x16 \x03(\v23.grpc.runtime.testpb.ABitOfEverything.MapValueEntryR\bmapValue\x12l\n" +
	"\x13mapped_string_value\x18\x17 \x03(\v2<.grpc.runtime.testpb.ABitOfEverything.MappedStringValueEntryR\x11mappedStringValue\x12l\n" +
	"\x13mapped_nested_value\x18\x18 \x03(\v2<.grpc.runtime.testpb.ABitOfEverything.MappedNestedValueEntryR\x11mappedNestedValue\x12:\n" +
	"\x18nonConventionalNameValue\x18\x1a \x01(\tR\x18nonConventionalNameValue\x12C\n" +
	"\x0ftimestamp_value\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampValue\x12P\n" +
	"\x13repeated_enum_value\x18\x1c \x03(\x0e2 .grpc.runtime.testpb.NumericEnumR\x11repeatedEnumValue\x12Z\n" +
	"\x18repeated_enum_annotation\x18  \x03(\x0e2 .grpc.runtime.testpb.NumericEnumR\x16repeatedEnumAnnotation\x12T\n" +
	"\x15enum_value_annotation\x18! \x01(\x0e2 .grpc.runtime.testpb.NumericEnumR\x13enumValueAnnotation\x12<\n" +
	"\x1arepeated_string_annotation\x18\" \x03(\tR\x18repeatedStringAnnotation\x12j\n" +
	"\x1arepeated_nested_annotation\x18# \x03(\v2,.grpc.runtime.testpb.ABitOfEverything.NestedR\x18repeatedNestedAnnotation\x12Y\n" +
	"\x11nested_annotation\x18$ \x01(\v2,.grpc.runtime.testpb.ABitOfEverything.NestedR\x10nestedAnnotation\x12.\n" +
	"\x13int64_override_type\x18% \x01(\x03R\x11int64OverrideType\x12.\n" +
	"\aanytype\x18& \x01(\v2\x14.google.protobuf.AnyR\aanytype\x12?\n" +
	"\x10repeated_anytype\x18' \x03(\v2\x14.google.protobuf.AnyR\x0frepeatedAnytype\x1a\x9c\x01\n" +
	"\x06Nested\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\x12E\n" +
	"\x02ok\x18\x03 \x01(\x0e25.grpc.runtime.testpb.ABitOfEverything.Nested.DeepEnumR\x02ok\"\x1f\n" +
	"\bDeepEnum\x12\t\n" +
	"\x05FALSE\x10\x00\x12\b\n" +
	"\x04TRUE\x10\x01\x1a]\n" +
	"\rMapValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\x0e2 .grpc.runtime.testpb.NumericEnumR\x05value:\x028\x01\x1aD\n" +
	"\x16MappedStringValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1ar\n" +
	"\x16MappedNestedValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12B\n" +
	"\x05value\x18\x02 \x01(\v2,.grpc.runtime.testpb.ABitOfEverything.NestedR\x05value:\x028\x01B\r\n" +
	"\voneof_value\"|\n" +
	"\x0fResponseBodyOut\x12I\n" +
	"\bresponse\x18\x02 \x01(\v2-.grpc.runtime.testpb.ResponseBodyOut.ResponseR\bresponse\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\x90\x02\n" +
	"\x17RepeatedResponseBodyOut\x12Q\n" +
	"\bresponse\x18\x02 \x03(\v25.grpc.runtime.testpb.RepeatedResponseBodyOut.ResponseR\bresponse\x1a\xa1\x01\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12V\n" +
	"\x04type\x18\x03 \x01(\x0e2B.grpc.runtime.testpb.RepeatedResponseBodyOut.Response.ResponseTypeR\x04type\")\n" +
	"\fResponseType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x05\n" +
	"\x01A\x10\x01\x12\x05\n" +
	"\x01B\x10\x02\"\xa2\x01\n" +
	"\rUpdateMessage\x12;\n" +
	"\vupdate_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12T\n" +
	"\x13a_bit_of_everything\x18\x02 \x01(\v2%.grpc.runtime.testpb.ABitOfEverythingR\x10aBitOfEverything\"?\n" +
	"\vNestedOuter\x120\n" +
	"\x03one\x18\x01 \x01(\v2\x1e.grpc.runtime.testpb.NestedOneR\x03one\"=\n" +
	"\tNestedOne\x120\n" +
	"\x03two\x18\x01 \x01(\v2\x1e.grpc.runtime.testpb.NestedTwoR\x03two\"C\n" +
	"\tNestedTwo\x126\n" +
	"\x05three\x18\x01 \x01(\v2 .grpc.runtime.testpb.NestedThreeR\x05three\")\n" +
	"\vNestedThree\x12\f\n" +
	"\x01a\x18\x01 \x01(\bR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\bR\x01b\"\x8c\x01\n" +
	"\x13UpdateNestedRequest\x128\n" +
	"\x06nested\x18\x01 \x01(\v2 .grpc.runtime.testpb.NestedOuterR\x06nested\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask* \n" +
	"\vNumericEnum\x12\b\n" +
	"\x04ZERO\x10\x00\x12\a\n" +
	"\x03ONE\x10\x01B)Z'github.com/kamalyes/grpc-runtime/testpbb\x06proto3"

var (
	file_testpb_example_proto_rawDescOnce sync.Once
	file_testpb_example_proto_rawDescData []byte
)

func file_testpb_example_proto_rawDescGZIP() []byte {
	file_testpb_example_proto_rawDescOnce.Do(func() {
		file_testpb_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_example_proto_rawDesc), len(file_testpb_example_proto_rawDesc)))
	})
	return file_testpb_example_proto_rawDescData
}

var file_testpb_example_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_testpb_example_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_testpb_example_proto_goTypes = []any{
	(NumericEnum)(0),                                   // 0: grpc.runtime.testpb.NumericEnum
	(ABitOfEverything_Nested_DeepEnum)(0),              // 1: grpc.runtime.testpb.ABitOfEverything.Nested.DeepEnum
	(RepeatedResponseBodyOut_Response_ResponseType)(0), // 2: grpc.runtime.testpb.RepeatedResponseBodyOut.Response.ResponseType
	(*SimpleMessage)(nil),                              // 3: grpc.runtime.testpb.SimpleMessage
	(*ABitOfEverything)(nil),                           // 4: grpc.runtime.testpb.ABitOfEverything
	(*ResponseBodyOut)(nil),                            // 5: grpc.runtime.testpb.ResponseBodyOut
	(*RepeatedResponseBodyOut)(nil),                    // 6: grpc.runtime.testpb.RepeatedResponseBodyOut
	(*UpdateMessage)(nil),                              // 7: grpc.runtime.testpb.UpdateMessage
	(*NestedOuter)(nil),                                // 8: grpc.runtime.testpb.NestedOuter
	(*NestedOne)(nil),                                  // 9: grpc.runtime.testpb.NestedOne
	(*NestedTwo)(nil),                                  // 10: grpc.runtime.testpb.NestedTwo
	(*NestedThree)(nil),                                // 11: grpc.runtime.testpb.NestedThree
	(*UpdateNestedRequest)(nil),                        // 12: grpc.runtime.testpb.UpdateNestedRequest
	(*ABitOfEverything_Nested)(nil),                    // 13: grpc.runtime.testpb.ABitOfEverything.Nested
	nil,                                                // 14: grpc.runtime.testpb.ABitOfEverything.MapValueEntry
	nil,                                                // 15: grpc.runtime.testpb.ABitOfEverything.MappedStringValueEntry
	nil,                                                // 16: grpc.runtime.testpb.ABitOfEverything.MappedNestedValueEntry
	(*ResponseBodyOut_Response)(nil),                   // 17: grpc.runtime.testpb.ResponseBodyOut.Response
	(*RepeatedResponseBodyOut_Response)(nil),           // 18: grpc.runtime.testpb.RepeatedResponseBodyOut.Response
	(*emptypb.Empty)(nil),                              // 19: google.protobuf.Empty
	(*timestamppb.Timestamp)(nil),                      // 20: google.protobuf.Timestamp
	(*anypb.Any)(nil),                                  // 21: google.protobuf.Any
	(*fieldmaskpb.FieldMask)(nil),                      // 22: google.protobuf.FieldMask
}
var file_testpb_example_proto_depIdxs = []int32{
	13, // 0: grpc.runtime.testpb.ABitOfEverything.single_nested:type_name -> grpc.runtime.testpb.ABitOfEverything.Nested
	13, // 1: grpc.runtime.testpb.ABitOfEverything.nested:type_name -> grpc.runtime.testpb.ABitOfEverything.Nested
	0,  // 2: grpc.runtime.testpb.ABitOfEverything.enum_value:type_name -> grpc.runtime.testpb.NumericEnum
	19, // 3: grpc.runtime.testpb.ABitOfEverything.oneof_empty:type_name -> google.protobuf.Empty
	14, // 4: grpc.runtime.testpb.ABitOfEverything.map_value:type_name -> grpc.runtime.testpb.ABitOfEverything.MapValueEntry
	15, // 5: grpc.runtime.testpb.ABitOfEverything.mapped_string_value:type_name -> grpc.runtime.testpb.ABitOfEverything.MappedStringValueEntry
	16, // 6: grpc.runtime.testpb.ABitOfEverything.mapped_nested_value:type_name -> grpc.runtime.testpb.ABitOfEverything.MappedNestedValueEntry
	20, // 7: grpc.runtime.testpb.ABitOfEverything.timestamp_value:type_name -> google.protobuf.Timestamp
	0,  // 8: grpc.runtime.testpb.ABitOfEverything.repeated_enum_value:type_name -> grpc.runtime.testpb.NumericEnum
	0,  // 9: grpc.runtime.testpb.ABitOfEverything.repeated_enum_annotation:type_name -> grpc.runtime.testpb.NumericEnum
	0,  // 10: grpc.runtime.testpb.ABitOfEverything.enum_value_annotation:type_name -> grpc.runtime.testpb.NumericEnum
	13, // 11: grpc.runtime.testpb.ABitOfEverything.repeated_nested_annotation:type_name -> grpc.runtime.testpb.ABitOfEverything.Nested
	13, // 12: grpc.runtime.testpb.ABitOfEverything.nested_annotation:type_name -> grpc.runtime.testpb.ABitOfEverything.Nested
	21, // 13: grpc.runtime.testpb.ABitOfEverything.anytype:type_name -> google.protobuf.Any
	21, // 14: grpc.runtime.testpb.ABitOfEverything.repeated_anytype:type_name -> google.protobuf.Any
	17, // 15: grpc.runtime.testpb.ResponseBodyOut.response:type_name -> grpc.runtime.testpb.ResponseBodyOut.Response
	18, // 16: grpc.runtime.testpb.RepeatedResponseBodyOut.response:type_name -> grpc.runtime.testpb.RepeatedResponseBodyOut.Response
	22, // 17: grpc.runtime.testpb.UpdateMessage.update_mask:type_name -> google.protobuf.FieldMask
	4,  // 18: grpc.runtime.testpb.UpdateMessage.a_bit_of_everything:type_name -> grpc.runtime.testpb.ABitOfEverything
	9,  // 19: grpc.runtime.testpb.NestedOuter.one:type_name -> grpc.runtime.testpb.NestedOne
	10, // 20: grpc.runtime.testpb.NestedOne.two:type_name -> grpc.runtime.testpb.NestedTwo
	11, // 21: grpc.runtime.testpb.NestedTwo.three:type_name -> grpc.runtime.testpb.NestedThree
	8,  // 22: grpc.runtime.testpb.UpdateNestedRequest.nested:type_name -> grpc.runtime.testpb.NestedOuter
	22, // 23: grpc.runtime.testpb.UpdateNestedRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 24: grpc.runtime.testpb.ABitOfEverything.Nested.ok:type_name -> grpc.runtime.testpb.ABitOfEverything.Nested.DeepEnum
	0,  // 25: grpc.runtime.testpb.ABitOfEverything.MapValueEntry.value:type_name -> grpc.runtime.testpb.NumericEnum
	13, // 26: grpc.runtime.testpb.ABitOfEverything.MappedNestedValueEntry.value:type_name -> grpc.runtime.testpb.ABitOfEverything.Nested
	2,  // 27: grpc.runtime.testpb.RepeatedResponseBodyOut.Response.type:type_name -> grpc.runtime.testpb.RepeatedResponseBodyOut.Response.ResponseType
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_testpb_example_proto_init() }
func file_testpb_example_proto_init() {
	if File_testpb_example_proto != nil {
		return
	}
	file_testpb_example_proto_msgTypes[1].OneofWrappers = []any{
		(*ABitOfEverything_OneofEmpty)(nil),
		(*ABitOfEverything_OneofString)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_example_proto_rawDesc), len(file_testpb_example_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testpb_example_proto_goTypes,
		DependencyIndexes: file_testpb_example_proto_depIdxs,
		EnumInfos:         file_testpb_example_proto_enumTypes,
		MessageInfos:      file_testpb_example_proto_msgTypes,
	}.Build()
	File_testpb_example_proto = out.File
	file_testpb_example_proto_goTypes = nil
	file_testpb_example_proto_depIdxs = nil
}
