// 非标准命名消息与服务定义 | [EN] Non-standard name messages and service definitions.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: testpb/non_standard_names.proto

package testpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NonStandardMessage 包含非常规字段名 | [EN] Message with non-standard protobuf field names.
type NonStandardMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 消息唯一标识 | [EN] Message identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Num 大写开头的数字字段 | [EN] Numeric field starting with an uppercase letter.
	Num int64 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	// line_num 下划线分隔的行号字段 | [EN] Snake-case line number field.
	LineNum int64 `protobuf:"varint,3,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	// langIdent 驼峰命名的语言标识 | [EN] Camel-case language identifier.
	LangIdent string `protobuf:"bytes,4,opt,name=langIdent,proto3" json:"langIdent,omitempty"`
	// STATUS 全大写状态字段 | [EN] Uppercase status field.
	STATUS string `protobuf:"bytes,5,opt,name=STATUS,proto3" json:"STATUS,omitempty"`
	// en_GB 包含地区代码的字段 | [EN] Field with region code.
	En_GB int64 `protobuf:"varint,6,opt,name=en_GB,json=enGB,proto3" json:"en_GB,omitempty"`
	// no 与 Go 关键字冲突的字段 | [EN] Field colliding with a Go keyword.
	No string `protobuf:"bytes,7,opt,name=no,proto3" json:"no,omitempty"`
	// thing 对象字段 | [EN] Thing field.
	Thing *NonStandardMessage_Thing `protobuf:"bytes,8,opt,name=thing,proto3" json:"thing,omitempty"`
	// struct_field Struct 类型字段 | [EN] Struct field.
	StructField *structpb.Struct `protobuf:"bytes,9,opt,name=struct_field,json=structField,proto3" json:"struct_field,omitempty"`
	// value_field Value 类型字段 | [EN] Value field.
	ValueField    *structpb.Value `protobuf:"bytes,10,opt,name=value_field,json=valueField,proto3" json:"value_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessage) Reset() {
	*x = NonStandardMessage{}
	mi := &file_testpb_non_standard_names_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessage) ProtoMessage() {}

func (x *NonStandardMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_non_standard_names_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessage.ProtoReflect.Descriptor instead.
func (*NonStandardMessage) Descriptor() ([]byte, []int) {
	return file_testpb_non_standard_names_proto_rawDescGZIP(), []int{0}
}

func (x *NonStandardMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NonStandardMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *NonStandardMessage) GetLineNum() int64 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

func (x *NonStandardMessage) GetLangIdent() string {
	if x != nil {
		return x.LangIdent
	}
	return ""
}

func (x *NonStandardMessage) GetSTATUS() string {
	if x != nil {
		return x.STATUS
	}
	return ""
}

func (x *NonStandardMessage) GetEn_GB() int64 {
	if x != nil {
		return x.En_GB
	}
	return 0
}

func (x *NonStandardMessage) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *NonStandardMessage) GetThing() *NonStandardMessage_Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

func (x *NonStandardMessage) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

func (x *NonStandardMessage) GetValueField() *structpb.Value {
	if x != nil {
		return x.ValueField
	}
	return nil
}

// NonStandardUpdateRequest 非标准消息更新请求 | [EN] Update request for NonStandardMessage.
type NonStandardUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// body 请求体 | [EN] Request body.
	Body *NonStandardMessage `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// update_mask 更新字段掩码 | [EN] Update field mask.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardUpdateRequest) Reset() {
	*x = NonStandardUpdateRequest{}
	mi := &file_testpb_non_standard_names_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardUpdateRequest) ProtoMessage() {}

func (x *NonStandardUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_non_standard_names_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardUpdateRequest.ProtoReflect.Descriptor instead.
func (*NonStandardUpdateRequest) Descriptor() ([]byte, []int) {
	return file_testpb_non_standard_names_proto_rawDescGZIP(), []int{1}
}

func (x *NonStandardUpdateRequest) GetBody() *NonStandardMessage {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NonStandardUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// NonStandardMessageWithJSONNames 带自定义 JSON 名称的非标准消息 | [EN] Non-standard message with custom JSON names.
type NonStandardMessageWithJSONNames struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id 消息唯一标识 | [EN] Message identifier.
	Id string `protobuf:"bytes,1,opt,name=id,json=ID,proto3" json:"id,omitempty"`
	// Num 大写开头的数字字段 | [EN] Numeric field starting with an uppercase letter.
	Num int64 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	// line_num 行号字段 | [EN] Line number field.
	LineNum int64 `protobuf:"varint,3,opt,name=line_num,json=LineNum,proto3" json:"line_num,omitempty"`
	// langIdent 语言标识字段 | [EN] Language identifier field.
	LangIdent string `protobuf:"bytes,4,opt,name=langIdent,proto3" json:"langIdent,omitempty"`
	// STATUS 状态字段 | [EN] Status field.
	STATUS string `protobuf:"bytes,5,opt,name=STATUS,json=status,proto3" json:"STATUS,omitempty"`
	// en_GB 地区代码字段 | [EN] Region code field.
	En_GB int64 `protobuf:"varint,6,opt,name=en_GB,json=En_GB,proto3" json:"en_GB,omitempty"`
	// no 与 Go 关键字冲突的字段 | [EN] Field colliding with a Go keyword.
	No string `protobuf:"bytes,7,opt,name=no,json=yes,proto3" json:"no,omitempty"`
	// thing 对象字段 | [EN] Thing field.
	Thing *NonStandardMessageWithJSONNames_Thing `protobuf:"bytes,8,opt,name=thing,json=Thingy,proto3" json:"thing,omitempty"`
	// struct_field Struct 类型字段 | [EN] Struct field.
	StructField *structpb.Struct `protobuf:"bytes,9,opt,name=struct_field,json=StructField,proto3" json:"struct_field,omitempty"`
	// value_field Value 类型字段 | [EN] Value field.
	ValueField    *structpb.Value `protobuf:"bytes,10,opt,name=value_field,json=ValueField,proto3" json:"value_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessageWithJSONNames) Reset() {
	*x = NonStandardMessageWithJSONNames{}
	mi := &file_testpb_non_standard_names_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessageWithJSONNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessageWithJSONNames) ProtoMessage() {}

func (x *NonStandardMessageWithJSONNames) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_non_standard_names_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessageWithJSONNames.ProtoReflect.Descriptor instead.
func (*NonStandardMessageWithJSONNames) Descriptor() ([]byte, []int) {
	return file_testpb_non_standard_names_proto_rawDescGZIP(), []int{2}
}

func (x *NonStandardMessageWithJSONNames) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *NonStandardMessageWithJSONNames) GetLineNum() int64 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

func (x *NonStandardMessageWithJSONNames) GetLangIdent() string {
	if x != nil {
		return x.LangIdent
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetSTATUS() string {
	if x != nil {
		return x.STATUS
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetEn_GB() int64 {
	if x != nil {
		return x.En_GB
	}
	return 0
}

func (x *NonStandardMessageWithJSONNames) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetThing() *NonStandardMessageWithJSONNames_Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

func (x *NonStandardMessageWithJSONNames) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

func (x *NonStandardMessageWithJSONNames) GetValueField() *structpb.Value {
	if x != nil {
		return x.ValueField
	}
	return nil
}

// NonStandardWithJSONNamesUpdateRequest 自定义 JSON 名称消息更新请求 | [EN] Update request for custom JSON-name message.
type NonStandardWithJSONNamesUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// body 请求体 | [EN] Request body.
	Body *NonStandardMessageWithJSONNames `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	// update_mask 更新字段掩码 | [EN] Update field mask.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardWithJSONNamesUpdateRequest) Reset() {
	*x = NonStandardWithJSONNamesUpdateRequest{}
	mi := &file_testpb_non_standard_names_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardWithJSONNamesUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardWithJSONNamesUpdateRequest) ProtoMessage() {}

func (x *NonStandardWithJSONNamesUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_non_standard_names_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardWithJSONNamesUpdateRequest.ProtoReflect.Descriptor instead.
func (*NonStandardWithJSONNamesUpdateRequest) Descriptor() ([]byte, []int) {
	return file_testpb_non_standard_names_proto_rawDescGZIP(), []int{3}
}

func (x *NonStandardWithJSONNamesUpdateRequest) GetBody() *NonStandardMessageWithJSONNames {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NonStandardWithJSONNamesUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// Thing 嵌套对象类型 | [EN] Nested thing type.
type NonStandardMessage_Thing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subThing 子对象实例 | [EN] Sub-thing instance.
	SubThing      *NonStandardMessage_Thing_SubThing `protobuf:"bytes,1,opt,name=subThing,proto3" json:"subThing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessage_Thing) Reset() {
	*x = NonStandardMessage_Thing{}
	mi := &file_testpb_non_standard_names_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessage_Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessage_Thing) ProtoMessage() {}

func (x *NonStandardMessage_Thing) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_non_standard_names_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessage_Thing.ProtoReflect.Descriptor instead.
func (*NonStandardMessage_Thing) Descriptor() ([]byte, []int) {
	return file_testpb_non_standard_names_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NonStandardMessage_Thing) GetSubThing() *NonStandardMessage_Thing_SubThing {
	if x != nil {
		return x.SubThing
	}
	return nil
}

// SubThing 子对象类型 | [EN] Nested sub-thing type.
type NonStandardMessage_Thing_SubThing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sub_value 子对象值 | [EN] Sub-thing value.
	SubValue      string `protobuf:"bytes,1,opt,name=sub_value,json=subValue,proto3" json:"sub_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessage_Thing_SubThing) Reset() {
	*x = NonStandardMessage_Thing_SubThing{}
	mi := &file_testpb_non_standard_names_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessage_Thing_SubThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessage_Thing_SubThing) ProtoMessage() {}

func (x *NonStandardMessage_Thing_SubThing) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_non_standard_names_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessage_Thing_SubThing.ProtoReflect.Descriptor instead.
func (*NonStandardMessage_Thing_SubThing) Descriptor() ([]byte, []int) {
	return file_testpb_non_standard_names_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *NonStandardMessage_Thing_SubThing) GetSubValue() string {
	if x != nil {
		return x.SubValue
	}
	return ""
}

// Thing 嵌套对象类型 | [EN] Nested thing type.
type NonStandardMessageWithJSONNames_Thing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subThing 子对象实例 | [EN] Sub-thing instance.
	SubThing      *NonStandardMessageWithJSONNames_Thing_SubThing `protobuf:"bytes,1,opt,name=subThing,json=SubThing,proto3" json:"subThing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessageWithJSONNames_Thing) Reset() {
	*x = NonStandardMessageWithJSONNames_Thing{}
	mi := &file_testpb_non_standard_names_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessageWithJSONNames_Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessageWithJSONNames_Thing) ProtoMessage() {}

func (x *NonStandardMessageWithJSONNames_Thing) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_non_standard_names_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessageWithJSONNames_Thing.ProtoReflect.Descriptor instead.
func (*NonStandardMessageWithJSONNames_Thing) Descriptor() ([]byte, []int) {
	return file_testpb_non_standard_names_proto_rawDescGZIP(), []int{2, 0}
}

func (x *NonStandardMessageWithJSONNames_Thing) GetSubThing() *NonStandardMessageWithJSONNames_Thing_SubThing {
	if x != nil {
		return x.SubThing
	}
	return nil
}

// SubThing 子对象类型 | [EN] Nested sub-thing type.
type NonStandardMessageWithJSONNames_Thing_SubThing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sub_value 子对象值 | [EN] Sub-thing value.
	SubValue      string `protobuf:"bytes,1,opt,name=sub_value,json=sub_Value,proto3" json:"sub_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) Reset() {
	*x = NonStandardMessageWithJSONNames_Thing_SubThing{}
	mi := &file_testpb_non_standard_names_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessageWithJSONNames_Thing_SubThing) ProtoMessage() {}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_non_standard_names_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessageWithJSONNames_Thing_SubThing.ProtoReflect.Descriptor instead.
func (*NonStandardMessageWithJSONNames_Thing_SubThing) Descriptor() ([]byte, []int) {
	return file_testpb_non_standard_names_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) GetSubValue() string {
	if x != nil {
		return x.SubValue
	}
	return ""
}

var File_testpb_non_standard_names_proto protoreflect.FileDescriptor

const file_testpb_non_standard_names_proto_rawDesc = "" +
	"\n" +
	"\x1ftestpb/non_standard_names.proto\x12\x13grpc.runtime.testpb\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xed\x03\n" +
	"\x12NonStandardMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x03R\x03Num\x12\x19\n" +
	"\bline_num\x18\x03 \x01(\x03R\alineNum\x12\x1c\n" +
	"\tlangIdent\x18\x04 \x01(\tR\tlangIdent\x12\x16\n" +
	"\x06STATUS\x18\x05 \x01(\tR\x06STATUS\x12\x13\n" +
	"\x05en_GB\x18\x06 \x01(\x03R\x04enGB\x12\x0e\n" +
	"\x02no\x18\a \x01(\tR\x02no\x12C\n" +
	"\x05thing\x18\b \x01(\v2-.grpc.runtime.testpb.NonStandardMessage.ThingR\x05thing\x12:\n" +
	"\fstruct_field\x18\t \x01(\v2\x17.google.protobuf.StructR\vstructField\x127\n" +
	"\vvalue_field\x18\n" +
	" \x01(\v2\x16.google.protobuf.ValueR\n" +
	"valueField\x1a\x84\x01\n" +
	"\x05Thing\x12R\n" +
	"\bsubThing\x18\x01 \x01(\v26.grpc.runtime.testpb.NonStandardMessage.Thing.SubThingR\bsubThing\x1a'\n" +
	"\bSubThing\x12\x1b\n" +
	"\tsub_value\x18\x01 \x01(\tR\bsubValue\"\x94\x01\n" +
	"\x18NonStandardUpdateRequest\x12;\n" +
	"\x04body\x18\x01 \x01(\v2'.grpc.runtime.testpb.NonStandardMessageR\x04body\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x98\x04\n" +
	"\x1fNonStandardMessageWithJSONNames\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x03R\x03Num\x12\x19\n" +
	"\bline_num\x18\x03 \x01(\x03R\aLineNum\x12\x1c\n" +
	"\tlangIdent\x18\x04 \x01(\tR\tlangIdent\x12\x16\n" +
	"\x06STATUS\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05en_GB\x18\x06 \x01(\x03R\x05En_GB\x12\x0f\n" +
	"\x02no\x18\a \x01(\tR\x03yes\x12Q\n" +
	"\x05thing\x18\b \x01(\v2:.grpc.runtime.testpb.NonStandardMessageWithJSONNames.ThingR\x06Thingy\x12:\n" +
	"\fstruct_field\x18\t \x01(\v2\x17.google.protobuf.StructR\vStructField\x127\n" +
	"\vvalue_field\x18\n" +
	" \x01(\v2\x16.google.protobuf.ValueR\n" +
	"ValueField\x1a\x92\x01\n" +
	"\x05Thing\x12_\n" +
	"\bsubThing\x18\x01 \x01(\v2C.grpc.runtime.testpb.NonStandardMessageWithJSONNames.Thing.SubThingR\bSubThing\x1a(\n" +
	"\bSubThing\x12\x1c\n" +
	"\tsub_value\x18\x01 \x01(\tR\tsub_Value\"\xae\x01\n" +
	"%NonStandardWithJSONNamesUpdateRequest\x12H\n" +
	"\x04body\x18\x01 \x01(\v24.grpc.runtime.testpb.NonStandardMessageWithJSONNamesR\x04body\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask2\xef\x02\n" +
	"\x12NonStandardService\x12\x8f\x01\n" +
	"\x06Update\x12-.grpc.runtime.testpb.NonStandardUpdateRequest\x1a'.grpc.runtime.testpb.NonStandardMessage\"-\x82\xd3\xe4\x93\x02':\x04body2\x1f/v1/example/non_standard/update\x12\xc6\x01\n" +
	"\x13UpdateWithJSONNames\x12:.grpc.runtime.testpb.NonStandardWithJSONNamesUpdateRequest\x1a4.grpc.runtime.testpb.NonStandardMessageWithJSONNames\"=\x82\xd3\xe4\x93\x027:\x04body2//v1/example/non_standard/update_with_json_namesB)Z'github.com/kamalyes/grpc-runtime/testpbb\x06proto3"

var (
	file_testpb_non_standard_names_proto_rawDescOnce sync.Once
	file_testpb_non_standard_names_proto_rawDescData []byte
)

func file_testpb_non_standard_names_proto_rawDescGZIP() []byte {
	file_testpb_non_standard_names_proto_rawDescOnce.Do(func() {
		file_testpb_non_standard_names_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_non_standard_names_proto_rawDesc), len(file_testpb_non_standard_names_proto_rawDesc)))
	})
	return file_testpb_non_standard_names_proto_rawDescData
}

var file_testpb_non_standard_names_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_testpb_non_standard_names_proto_goTypes = []any{
	(*NonStandardMessage)(nil),                             // 0: grpc.runtime.testpb.NonStandardMessage
	(*NonStandardUpdateRequest)(nil),                       // 1: grpc.runtime.testpb.NonStandardUpdateRequest
	(*NonStandardMessageWithJSONNames)(nil),                // 2: grpc.runtime.testpb.NonStandardMessageWithJSONNames
	(*NonStandardWithJSONNamesUpdateRequest)(nil),          // 3: grpc.runtime.testpb.NonStandardWithJSONNamesUpdateRequest
	(*NonStandardMessage_Thing)(nil),                       // 4: grpc.runtime.testpb.NonStandardMessage.Thing
	(*NonStandardMessage_Thing_SubThing)(nil),              // 5: grpc.runtime.testpb.NonStandardMessage.Thing.SubThing
	(*NonStandardMessageWithJSONNames_Thing)(nil),          // 6: grpc.runtime.testpb.NonStandardMessageWithJSONNames.Thing
	(*NonStandardMessageWithJSONNames_Thing_SubThing)(nil), // 7: grpc.runtime.testpb.NonStandardMessageWithJSONNames.Thing.SubThing
	(*structpb.Struct)(nil),                                // 8: google.protobuf.Struct
	(*structpb.Value)(nil),                                 // 9: google.protobuf.Value
	(*fieldmaskpb.FieldMask)(nil),                          // 10: google.protobuf.FieldMask
}
var file_testpb_non_standard_names_proto_depIdxs = []int32{
	4,  // 0: grpc.runtime.testpb.NonStandardMessage.thing:type_name -> grpc.runtime.testpb.NonStandardMessage.Thing
	8,  // 1: grpc.runtime.testpb.NonStandardMessage.struct_field:type_name -> google.protobuf.Struct
	9,  // 2: grpc.runtime.testpb.NonStandardMessage.value_field:type_name -> google.protobuf.Value
	0,  // 3: grpc.runtime.testpb.NonStandardUpdateRequest.body:type_name -> grpc.runtime.testpb.NonStandardMessage
	10, // 4: grpc.runtime.testpb.NonStandardUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	6,  // 5: grpc.runtime.testpb.NonStandardMessageWithJSONNames.thing:type_name -> grpc.runtime.testpb.NonStandardMessageWithJSONNames.Thing
	8,  // 6: grpc.runtime.testpb.NonStandardMessageWithJSONNames.struct_field:type_name -> google.protobuf.Struct
	9,  // 7: grpc.runtime.testpb.NonStandardMessageWithJSONNames.value_field:type_name -> google.protobuf.Value
	2,  // 8: grpc.runtime.testpb.NonStandardWithJSONNamesUpdateRequest.body:type_name -> grpc.runtime.testpb.NonStandardMessageWithJSONNames
	10, // 9: grpc.runtime.testpb.NonStandardWithJSONNamesUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	5,  // 10: grpc.runtime.testpb.NonStandardMessage.Thing.subThing:type_name -> grpc.runtime.testpb.NonStandardMessage.Thing.SubThing
	7,  // 11: grpc.runtime.testpb.NonStandardMessageWithJSONNames.Thing.subThing:type_name -> grpc.runtime.testpb.NonStandardMessageWithJSONNames.Thing.SubThing
	1,  // 12: grpc.runtime.testpb.NonStandardService.Update:input_type -> grpc.runtime.testpb.NonStandardUpdateRequest
	3,  // 13: grpc.runtime.testpb.NonStandardService.UpdateWithJSONNames:input_type -> grpc.runtime.testpb.NonStandardWithJSONNamesUpdateRequest
	0,  // 14: grpc.runtime.testpb.NonStandardService.Update:output_type -> grpc.runtime.testpb.NonStandardMessage
	2,  // 15: grpc.runtime.testpb.NonStandardService.UpdateWithJSONNames:output_type -> grpc.runtime.testpb.NonStandardMessageWithJSONNames
	14, // [14:16] is the sub-list for method output_type
	12, // [12:14] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_testpb_non_standard_names_proto_init() }
func file_testpb_non_standard_names_proto_init() {
	if File_testpb_non_standard_names_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_non_standard_names_proto_rawDesc), len(file_testpb_non_standard_names_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testpb_non_standard_names_proto_goTypes,
		DependencyIndexes: file_testpb_non_standard_names_proto_depIdxs,
		MessageInfos:      file_testpb_non_standard_names_proto_msgTypes,
	}.Build()
	File_testpb_non_standard_names_proto = out.File
	file_testpb_non_standard_names_proto_goTypes = nil
	file_testpb_non_standard_names_proto_depIdxs = nil
}
