// Proto2 字段类型测试消息 | [EN] Proto2 field type test messages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: testpb/proto2.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proto2Message 覆盖 proto2 optional/repeated 标量字段类型 | [EN] Covers proto2 optional and repeated scalar fields.
type Proto2Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// float_value 浮点数 | [EN] Float value.
	FloatValue *float32 `protobuf:"fixed32,42,opt,name=float_value,json=floatValue" json:"float_value,omitempty"`
	// double_value 双精度浮点数 | [EN] Double value.
	DoubleValue *float64 `protobuf:"fixed64,43,opt,name=double_value,json=doubleValue" json:"double_value,omitempty"`
	// int64_value 64 位整数 | [EN] int64 value.
	Int64Value *int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value" json:"int64_value,omitempty"`
	// int32_value 32 位整数 | [EN] int32 value.
	Int32Value *int32 `protobuf:"varint,4,opt,name=int32_value,json=int32Value" json:"int32_value,omitempty"`
	// uint64_value 无符号 64 位整数 | [EN] uint64 value.
	Uint64Value *uint64 `protobuf:"varint,5,opt,name=uint64_value,json=uint64Value" json:"uint64_value,omitempty"`
	// uint32_value 无符号 32 位整数 | [EN] uint32 value.
	Uint32Value *uint32 `protobuf:"varint,6,opt,name=uint32_value,json=uint32Value" json:"uint32_value,omitempty"`
	// bool_value 布尔值 | [EN] Boolean value.
	BoolValue *bool `protobuf:"varint,7,opt,name=bool_value,json=boolValue" json:"bool_value,omitempty"`
	// string_value 字符串 | [EN] String value.
	StringValue *string `protobuf:"bytes,8,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	// bytes_value 字节数组 | [EN] Bytes value.
	BytesValue []byte `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue" json:"bytes_value,omitempty"`
	// repeated_value 字符串列表 | [EN] Repeated string value.
	RepeatedValue []string `protobuf:"bytes,10,rep,name=repeated_value,json=repeatedValue" json:"repeated_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto2Message) Reset() {
	*x = Proto2Message{}
	mi := &file_testpb_proto2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto2Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto2Message) ProtoMessage() {}

func (x *Proto2Message) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto2Message.ProtoReflect.Descriptor instead.
func (*Proto2Message) Descriptor() ([]byte, []int) {
	return file_testpb_proto2_proto_rawDescGZIP(), []int{0}
}

func (x *Proto2Message) GetFloatValue() float32 {
	if x != nil && x.FloatValue != nil {
		return *x.FloatValue
	}
	return 0
}

func (x *Proto2Message) GetDoubleValue() float64 {
	if x != nil && x.DoubleValue != nil {
		return *x.DoubleValue
	}
	return 0
}

func (x *Proto2Message) GetInt64Value() int64 {
	if x != nil && x.Int64Value != nil {
		return *x.Int64Value
	}
	return 0
}

func (x *Proto2Message) GetInt32Value() int32 {
	if x != nil && x.Int32Value != nil {
		return *x.Int32Value
	}
	return 0
}

func (x *Proto2Message) GetUint64Value() uint64 {
	if x != nil && x.Uint64Value != nil {
		return *x.Uint64Value
	}
	return 0
}

func (x *Proto2Message) GetUint32Value() uint32 {
	if x != nil && x.Uint32Value != nil {
		return *x.Uint32Value
	}
	return 0
}

func (x *Proto2Message) GetBoolValue() bool {
	if x != nil && x.BoolValue != nil {
		return *x.BoolValue
	}
	return false
}

func (x *Proto2Message) GetStringValue() string {
	if x != nil && x.StringValue != nil {
		return *x.StringValue
	}
	return ""
}

func (x *Proto2Message) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *Proto2Message) GetRepeatedValue() []string {
	if x != nil {
		return x.RepeatedValue
	}
	return nil
}

var File_testpb_proto2_proto protoreflect.FileDescriptor

const file_testpb_proto2_proto_rawDesc = "" +
	"\n" +
	"\x13testpb/proto2.proto\x12\x13grpc.runtime.testpb\"\xe5\x02\n" +
	"\rProto2Message\x12\x1f\n" +
	"\vfloat_value\x18* \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18+ \x01(\x01R\vdoubleValue\x12\x1f\n" +
	"\vint64_value\x18\x03 \x01(\x03R\n" +
	"int64Value\x12\x1f\n" +
	"\vint32_value\x18\x04 \x01(\x05R\n" +
	"int32Value\x12!\n" +
	"\fuint64_value\x18\x05 \x01(\x04R\vuint64Value\x12!\n" +
	"\fuint32_value\x18\x06 \x01(\rR\vuint32Value\x12\x1d\n" +
	"\n" +
	"bool_value\x18\a \x01(\bR\tboolValue\x12!\n" +
	"\fstring_value\x18\b \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\t \x01(\fR\n" +
	"bytesValue\x12%\n" +
	"\x0erepeated_value\x18\n" +
	" \x03(\tR\rrepeatedValueB)Z'github.com/kamalyes/grpc-runtime/testpb"

var (
	file_testpb_proto2_proto_rawDescOnce sync.Once
	file_testpb_proto2_proto_rawDescData []byte
)

func file_testpb_proto2_proto_rawDescGZIP() []byte {
	file_testpb_proto2_proto_rawDescOnce.Do(func() {
		file_testpb_proto2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_proto2_proto_rawDesc), len(file_testpb_proto2_proto_rawDesc)))
	})
	return file_testpb_proto2_proto_rawDescData
}

var file_testpb_proto2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testpb_proto2_proto_goTypes = []any{
	(*Proto2Message)(nil), // 0: grpc.runtime.testpb.Proto2Message
}
var file_testpb_proto2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testpb_proto2_proto_init() }
func file_testpb_proto2_proto_init() {
	if File_testpb_proto2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_proto2_proto_rawDesc), len(file_testpb_proto2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testpb_proto2_proto_goTypes,
		DependencyIndexes: file_testpb_proto2_proto_depIdxs,
		MessageInfos:      file_testpb_proto2_proto_msgTypes,
	}.Build()
	File_testpb_proto2_proto = out.File
	file_testpb_proto2_proto_goTypes = nil
	file_testpb_proto2_proto_depIdxs = nil
}
