// Proto3 字段类型测试消息 | [EN] Proto3 field type test messages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.24.3
// source: testpb/proto3.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnumValue 测试枚举值 | [EN] Test enum values.
type EnumValue int32

const (
	// X 枚举值 X | [EN] Enum value X.
	EnumValue_X EnumValue = 0
	// Y 枚举值 Y | [EN] Enum value Y.
	EnumValue_Y EnumValue = 1
	// Z 枚举值 Z | [EN] Enum value Z.
	EnumValue_Z EnumValue = 2
)

// Enum value maps for EnumValue.
var (
	EnumValue_name = map[int32]string{
		0: "X",
		1: "Y",
		2: "Z",
	}
	EnumValue_value = map[string]int32{
		"X": 0,
		"Y": 1,
		"Z": 2,
	}
)

func (x EnumValue) Enum() *EnumValue {
	p := new(EnumValue)
	*p = x
	return p
}

func (x EnumValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumValue) Descriptor() protoreflect.EnumDescriptor {
	return file_testpb_proto3_proto_enumTypes[0].Descriptor()
}

func (EnumValue) Type() protoreflect.EnumType {
	return &file_testpb_proto3_proto_enumTypes[0]
}

func (x EnumValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumValue.Descriptor instead.
func (EnumValue) EnumDescriptor() ([]byte, []int) {
	return file_testpb_proto3_proto_rawDescGZIP(), []int{0}
}

// Proto3Message 覆盖 proto3 标量、Well-Known、map 与 oneof 字段 | [EN] Covers proto3 scalar, well-known, map and oneof fields.
type Proto3Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nested 嵌套自身消息 | [EN] Nested self message.
	Nested *Proto3Message `protobuf:"bytes,41,opt,name=nested,proto3" json:"nested,omitempty"`
	// float_value 浮点数 | [EN] Float value.
	FloatValue float32 `protobuf:"fixed32,42,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	// double_value 双精度浮点数 | [EN] Double value.
	DoubleValue float64 `protobuf:"fixed64,43,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	// int64_value 64 位整数 | [EN] int64 value.
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	// int32_value 32 位整数 | [EN] int32 value.
	Int32Value int32 `protobuf:"varint,4,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	// uint64_value 无符号 64 位整数 | [EN] uint64 value.
	Uint64Value uint64 `protobuf:"varint,5,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	// uint32_value 无符号 32 位整数 | [EN] uint32 value.
	Uint32Value uint32 `protobuf:"varint,6,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	// bool_value 布尔值 | [EN] Boolean value.
	BoolValue bool `protobuf:"varint,7,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	// string_value 字符串 | [EN] String value.
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	// bytes_value 字节数组 | [EN] Bytes value.
	BytesValue []byte `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	// repeated_value 字符串列表 | [EN] Repeated string value.
	RepeatedValue []string `protobuf:"bytes,10,rep,name=repeated_value,json=repeatedValue,proto3" json:"repeated_value,omitempty"`
	// optional_value proto3 optional 字段 | [EN] proto3 optional string value.
	OptionalValue *string `protobuf:"bytes,49,opt,name=optional_value,json=optionalValue,proto3,oneof" json:"optional_value,omitempty"`
	// repeated_message Well-Known 包装类型列表 | [EN] Repeated well-known wrapper messages.
	RepeatedMessage []*wrapperspb.UInt64Value `protobuf:"bytes,44,rep,name=repeated_message,json=repeatedMessage,proto3" json:"repeated_message,omitempty"`
	// enum_value 枚举值 | [EN] Enum value.
	EnumValue EnumValue `protobuf:"varint,11,opt,name=enum_value,json=enumValue,proto3,enum=grpc.runtime.testpb.EnumValue" json:"enum_value,omitempty"`
	// repeated_enum 枚举值列表 | [EN] Repeated enum values.
	RepeatedEnum []EnumValue `protobuf:"varint,12,rep,packed,name=repeated_enum,json=repeatedEnum,proto3,enum=grpc.runtime.testpb.EnumValue" json:"repeated_enum,omitempty"`
	// timestamp_value 时间戳 | [EN] Timestamp value.
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	// duration_value 持续时间 | [EN] Duration value.
	DurationValue *durationpb.Duration `protobuf:"bytes,14,opt,name=duration_value,json=durationValue,proto3" json:"duration_value,omitempty"`
	// fieldmask_value 字段掩码 | [EN] Field mask value.
	FieldmaskValue *fieldmaskpb.FieldMask `protobuf:"bytes,15,opt,name=fieldmask_value,json=fieldmaskValue,proto3" json:"fieldmask_value,omitempty"`
	// oneof_value 单值选择 | [EN] Oneof scalar selection.
	//
	// Types that are valid to be assigned to OneofValue:
	//
	//	*Proto3Message_OneofBoolValue
	//	*Proto3Message_OneofStringValue
	OneofValue isProto3Message_OneofValue `protobuf_oneof:"oneof_value"`
	// nested_oneof_value 嵌套 oneof | [EN] Nested oneof selection.
	//
	// Types that are valid to be assigned to NestedOneofValue:
	//
	//	*Proto3Message_NestedOneofInt32Value
	//	*Proto3Message_NestedOneofValueOne
	NestedOneofValue isProto3Message_NestedOneofValue `protobuf_oneof:"nested_oneof_value"`
	// wrapper_double_value Double 包装类型 | [EN] Double wrapper.
	WrapperDoubleValue *wrapperspb.DoubleValue `protobuf:"bytes,17,opt,name=wrapper_double_value,json=wrapperDoubleValue,proto3" json:"wrapper_double_value,omitempty"`
	// wrapper_float_value Float 包装类型 | [EN] Float wrapper.
	WrapperFloatValue *wrapperspb.FloatValue `protobuf:"bytes,18,opt,name=wrapper_float_value,json=wrapperFloatValue,proto3" json:"wrapper_float_value,omitempty"`
	// wrapper_int64_value Int64 包装类型 | [EN] Int64 wrapper.
	WrapperInt64Value *wrapperspb.Int64Value `protobuf:"bytes,19,opt,name=wrapper_int64_value,json=wrapperInt64Value,proto3" json:"wrapper_int64_value,omitempty"`
	// wrapper_int32_value Int32 包装类型 | [EN] Int32 wrapper.
	WrapperInt32Value *wrapperspb.Int32Value `protobuf:"bytes,20,opt,name=wrapper_int32_value,json=wrapperInt32Value,proto3" json:"wrapper_int32_value,omitempty"`
	// wrapper_u_int64_value UInt64 包装类型 | [EN] UInt64 wrapper.
	WrapperUInt64Value *wrapperspb.UInt64Value `protobuf:"bytes,21,opt,name=wrapper_u_int64_value,json=wrapperUInt64Value,proto3" json:"wrapper_u_int64_value,omitempty"`
	// wrapper_u_int32_value UInt32 包装类型 | [EN] UInt32 wrapper.
	WrapperUInt32Value *wrapperspb.UInt32Value `protobuf:"bytes,22,opt,name=wrapper_u_int32_value,json=wrapperUInt32Value,proto3" json:"wrapper_u_int32_value,omitempty"`
	// wrapper_bool_value Bool 包装类型 | [EN] Bool wrapper.
	WrapperBoolValue *wrapperspb.BoolValue `protobuf:"bytes,23,opt,name=wrapper_bool_value,json=wrapperBoolValue,proto3" json:"wrapper_bool_value,omitempty"`
	// wrapper_string_value String 包装类型 | [EN] String wrapper.
	WrapperStringValue *wrapperspb.StringValue `protobuf:"bytes,24,opt,name=wrapper_string_value,json=wrapperStringValue,proto3" json:"wrapper_string_value,omitempty"`
	// wrapper_bytes_value Bytes 包装类型 | [EN] Bytes wrapper.
	WrapperBytesValue *wrapperspb.BytesValue `protobuf:"bytes,25,opt,name=wrapper_bytes_value,json=wrapperBytesValue,proto3" json:"wrapper_bytes_value,omitempty"`
	// map_value 字符串到字符串映射 | [EN] string to string map.
	MapValue map[string]string `protobuf:"bytes,26,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// map_value2 字符串到 int32 映射 | [EN] string to int32 map.
	MapValue2 map[string]int32 `protobuf:"bytes,27,rep,name=map_value2,json=mapValue2,proto3" json:"map_value2,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// map_value3 int32 到字符串映射 | [EN] int32 to string map.
	MapValue3 map[int32]string `protobuf:"bytes,28,rep,name=map_value3,json=mapValue3,proto3" json:"map_value3,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// map_value4 字符串到 int64 映射 | [EN] string to int64 map.
	MapValue4 map[string]int64 `protobuf:"bytes,29,rep,name=map_value4,json=mapValue4,proto3" json:"map_value4,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// map_value5 int64 到字符串映射 | [EN] int64 to string map.
	MapValue5 map[int64]string `protobuf:"bytes,30,rep,name=map_value5,json=mapValue5,proto3" json:"map_value5,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// map_value6 字符串到 uint32 映射 | [EN] string to uint32 map.
	MapValue6 map[string]uint32 `protobuf:"bytes,31,rep,name=map_value6,json=mapValue6,proto3" json:"map_value6,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// map_value7 uint32 到字符串映射 | [EN] uint32 to string map.
	MapValue7 map[uint32]string `protobuf:"bytes,32,rep,name=map_value7,json=mapValue7,proto3" json:"map_value7,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// map_value8 字符串到 uint64 映射 | [EN] string to uint64 map.
	MapValue8 map[string]uint64 `protobuf:"bytes,33,rep,name=map_value8,json=mapValue8,proto3" json:"map_value8,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// map_value9 uint64 到字符串映射 | [EN] uint64 to string map.
	MapValue9 map[uint64]string `protobuf:"bytes,34,rep,name=map_value9,json=mapValue9,proto3" json:"map_value9,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// map_value10 字符串到 float 映射 | [EN] string to float map.
	MapValue10 map[string]float32 `protobuf:"bytes,35,rep,name=map_value10,json=mapValue10,proto3" json:"map_value10,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	// map_value12 字符串到 double 映射 | [EN] string to double map.
	MapValue12 map[string]float64 `protobuf:"bytes,37,rep,name=map_value12,json=mapValue12,proto3" json:"map_value12,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// map_value14 字符串到 bool 映射 | [EN] string to bool map.
	MapValue14 map[string]bool `protobuf:"bytes,39,rep,name=map_value14,json=mapValue14,proto3" json:"map_value14,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// map_value15 bool 到字符串映射 | [EN] bool to string map.
	MapValue15 map[bool]string `protobuf:"bytes,40,rep,name=map_value15,json=mapValue15,proto3" json:"map_value15,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// map_value16 字符串到 UInt64 包装类型映射 | [EN] string to UInt64 wrapper map.
	MapValue16 map[string]*wrapperspb.UInt64Value `protobuf:"bytes,45,rep,name=map_value16,json=mapValue16,proto3" json:"map_value16,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// struct_value_value Value 类型字段 | [EN] google.protobuf.Value field.
	StructValueValue *structpb.Value `protobuf:"bytes,47,opt,name=struct_value_value,json=structValueValue,proto3" json:"struct_value_value,omitempty"`
	// struct_value Struct 类型字段 | [EN] google.protobuf.Struct field.
	StructValue   *structpb.Struct `protobuf:"bytes,48,opt,name=struct_value,json=structValue,proto3" json:"struct_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proto3Message) Reset() {
	*x = Proto3Message{}
	mi := &file_testpb_proto3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proto3Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proto3Message) ProtoMessage() {}

func (x *Proto3Message) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proto3Message.ProtoReflect.Descriptor instead.
func (*Proto3Message) Descriptor() ([]byte, []int) {
	return file_testpb_proto3_proto_rawDescGZIP(), []int{0}
}

func (x *Proto3Message) GetNested() *Proto3Message {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *Proto3Message) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *Proto3Message) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *Proto3Message) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *Proto3Message) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *Proto3Message) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *Proto3Message) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *Proto3Message) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *Proto3Message) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *Proto3Message) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *Proto3Message) GetRepeatedValue() []string {
	if x != nil {
		return x.RepeatedValue
	}
	return nil
}

func (x *Proto3Message) GetOptionalValue() string {
	if x != nil && x.OptionalValue != nil {
		return *x.OptionalValue
	}
	return ""
}

func (x *Proto3Message) GetRepeatedMessage() []*wrapperspb.UInt64Value {
	if x != nil {
		return x.RepeatedMessage
	}
	return nil
}

func (x *Proto3Message) GetEnumValue() EnumValue {
	if x != nil {
		return x.EnumValue
	}
	return EnumValue_X
}

func (x *Proto3Message) GetRepeatedEnum() []EnumValue {
	if x != nil {
		return x.RepeatedEnum
	}
	return nil
}

func (x *Proto3Message) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampValue
	}
	return nil
}

func (x *Proto3Message) GetDurationValue() *durationpb.Duration {
	if x != nil {
		return x.DurationValue
	}
	return nil
}

func (x *Proto3Message) GetFieldmaskValue() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldmaskValue
	}
	return nil
}

func (x *Proto3Message) GetOneofValue() isProto3Message_OneofValue {
	if x != nil {
		return x.OneofValue
	}
	return nil
}

func (x *Proto3Message) GetOneofBoolValue() bool {
	if x != nil {
		if x, ok := x.OneofValue.(*Proto3Message_OneofBoolValue); ok {
			return x.OneofBoolValue
		}
	}
	return false
}

func (x *Proto3Message) GetOneofStringValue() string {
	if x != nil {
		if x, ok := x.OneofValue.(*Proto3Message_OneofStringValue); ok {
			return x.OneofStringValue
		}
	}
	return ""
}

func (x *Proto3Message) GetNestedOneofValue() isProto3Message_NestedOneofValue {
	if x != nil {
		return x.NestedOneofValue
	}
	return nil
}

func (x *Proto3Message) GetNestedOneofInt32Value() int32 {
	if x != nil {
		if x, ok := x.NestedOneofValue.(*Proto3Message_NestedOneofInt32Value); ok {
			return x.NestedOneofInt32Value
		}
	}
	return 0
}

func (x *Proto3Message) GetNestedOneofValueOne() *Proto3Message {
	if x != nil {
		if x, ok := x.NestedOneofValue.(*Proto3Message_NestedOneofValueOne); ok {
			return x.NestedOneofValueOne
		}
	}
	return nil
}

func (x *Proto3Message) GetWrapperDoubleValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.WrapperDoubleValue
	}
	return nil
}

func (x *Proto3Message) GetWrapperFloatValue() *wrapperspb.FloatValue {
	if x != nil {
		return x.WrapperFloatValue
	}
	return nil
}

func (x *Proto3Message) GetWrapperInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		return x.WrapperInt64Value
	}
	return nil
}

func (x *Proto3Message) GetWrapperInt32Value() *wrapperspb.Int32Value {
	if x != nil {
		return x.WrapperInt32Value
	}
	return nil
}

func (x *Proto3Message) GetWrapperUInt64Value() *wrapperspb.UInt64Value {
	if x != nil {
		return x.WrapperUInt64Value
	}
	return nil
}

func (x *Proto3Message) GetWrapperUInt32Value() *wrapperspb.UInt32Value {
	if x != nil {
		return x.WrapperUInt32Value
	}
	return nil
}

func (x *Proto3Message) GetWrapperBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		return x.WrapperBoolValue
	}
	return nil
}

func (x *Proto3Message) GetWrapperStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.WrapperStringValue
	}
	return nil
}

func (x *Proto3Message) GetWrapperBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.WrapperBytesValue
	}
	return nil
}

func (x *Proto3Message) GetMapValue() map[string]string {
	if x != nil {
		return x.MapValue
	}
	return nil
}

func (x *Proto3Message) GetMapValue2() map[string]int32 {
	if x != nil {
		return x.MapValue2
	}
	return nil
}

func (x *Proto3Message) GetMapValue3() map[int32]string {
	if x != nil {
		return x.MapValue3
	}
	return nil
}

func (x *Proto3Message) GetMapValue4() map[string]int64 {
	if x != nil {
		return x.MapValue4
	}
	return nil
}

func (x *Proto3Message) GetMapValue5() map[int64]string {
	if x != nil {
		return x.MapValue5
	}
	return nil
}

func (x *Proto3Message) GetMapValue6() map[string]uint32 {
	if x != nil {
		return x.MapValue6
	}
	return nil
}

func (x *Proto3Message) GetMapValue7() map[uint32]string {
	if x != nil {
		return x.MapValue7
	}
	return nil
}

func (x *Proto3Message) GetMapValue8() map[string]uint64 {
	if x != nil {
		return x.MapValue8
	}
	return nil
}

func (x *Proto3Message) GetMapValue9() map[uint64]string {
	if x != nil {
		return x.MapValue9
	}
	return nil
}

func (x *Proto3Message) GetMapValue10() map[string]float32 {
	if x != nil {
		return x.MapValue10
	}
	return nil
}

func (x *Proto3Message) GetMapValue12() map[string]float64 {
	if x != nil {
		return x.MapValue12
	}
	return nil
}

func (x *Proto3Message) GetMapValue14() map[string]bool {
	if x != nil {
		return x.MapValue14
	}
	return nil
}

func (x *Proto3Message) GetMapValue15() map[bool]string {
	if x != nil {
		return x.MapValue15
	}
	return nil
}

func (x *Proto3Message) GetMapValue16() map[string]*wrapperspb.UInt64Value {
	if x != nil {
		return x.MapValue16
	}
	return nil
}

func (x *Proto3Message) GetStructValueValue() *structpb.Value {
	if x != nil {
		return x.StructValueValue
	}
	return nil
}

func (x *Proto3Message) GetStructValue() *structpb.Struct {
	if x != nil {
		return x.StructValue
	}
	return nil
}

type isProto3Message_OneofValue interface {
	isProto3Message_OneofValue()
}

type Proto3Message_OneofBoolValue struct {
	// oneof_bool_value 布尔选项 | [EN] Boolean oneof option.
	OneofBoolValue bool `protobuf:"varint,1,opt,name=oneof_bool_value,json=oneofBoolValue,proto3,oneof"`
}

type Proto3Message_OneofStringValue struct {
	// oneof_string_value 字符串选项 | [EN] String oneof option.
	OneofStringValue string `protobuf:"bytes,2,opt,name=oneof_string_value,json=oneofStringValue,proto3,oneof"`
}

func (*Proto3Message_OneofBoolValue) isProto3Message_OneofValue() {}

func (*Proto3Message_OneofStringValue) isProto3Message_OneofValue() {}

type isProto3Message_NestedOneofValue interface {
	isProto3Message_NestedOneofValue()
}

type Proto3Message_NestedOneofInt32Value struct {
	// nested_oneof_int32_value 32 位整数选项 | [EN] int32 oneof option.
	NestedOneofInt32Value int32 `protobuf:"varint,50,opt,name=nested_oneof_int32_value,json=nestedOneofInt32Value,proto3,oneof"`
}

type Proto3Message_NestedOneofValueOne struct {
	// nested_oneof_value_one 消息选项 | [EN] Message oneof option.
	NestedOneofValueOne *Proto3Message `protobuf:"bytes,46,opt,name=nested_oneof_value_one,json=nestedOneofValueOne,proto3,oneof"`
}

func (*Proto3Message_NestedOneofInt32Value) isProto3Message_NestedOneofValue() {}

func (*Proto3Message_NestedOneofValueOne) isProto3Message_NestedOneofValue() {}

var File_testpb_proto3_proto protoreflect.FileDescriptor

const file_testpb_proto3_proto_rawDesc = "" +
	"\n" +
	"\x13testpb/proto3.proto\x12\x13grpc.runtime.testpb\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xe0\x1f\n" +
	"\rProto3Message\x12:\n" +
	"\x06nested\x18) \x01(\v2\".grpc.runtime.testpb.Proto3MessageR\x06nested\x12\x1f\n" +
	"\vfloat_value\x18* \x01(\x02R\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18+ \x01(\x01R\vdoubleValue\x12\x1f\n" +
	"\vint64_value\x18\x03 \x01(\x03R\n" +
	"int64Value\x12\x1f\n" +
	"\vint32_value\x18\x04 \x01(\x05R\n" +
	"int32Value\x12!\n" +
	"\fuint64_value\x18\x05 \x01(\x04R\vuint64Value\x12!\n" +
	"\fuint32_value\x18\x06 \x01(\rR\vuint32Value\x12\x1d\n" +
	"\n" +
	"bool_value\x18\a \x01(\bR\tboolValue\x12!\n" +
	"\fstring_value\x18\b \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\t \x01(\fR\n" +
	"bytesValue\x12%\n" +
	"\x0erepeated_value\x18\n" +
	" \x03(\tR\rrepeatedValue\x12*\n" +
	"\x0eoptional_value\x181 \x01(\tH\x02R\roptionalValue\x88\x01\x01\x12G\n" +
	"\x10repeated_message\x18, \x03(\v2\x1c.google.protobuf.UInt64ValueR\x0frepeatedMessage\x12=\n" +
	"\n" +
	"enum_value\x18\v \x01(\x0e2\x1e.grpc.runtime.testpb.EnumValueR\tenumValue\x12C\n" +
	"\rrepeated_enum\x18\f \x03(\x0e2\x1e.grpc.runtime.testpb.EnumValueR\frepeatedEnum\x12C\n" +
	"\x0ftimestamp_value\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampValue\x12@\n" +
	"\x0eduration_value\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\rdurationValue\x12C\n" +
	"\x0ffieldmask_value\x18\x0f \x01(\v2\x1a.google.protobuf.FieldMaskR\x0efieldmaskValue\x12*\n" +
	"\x10oneof_bool_value\x18\x01 \x01(\bH\x00R\x0eoneofBoolValue\x12.\n" +
	"\x12oneof_string_value\x18\x02 \x01(\tH\x00R\x10oneofStringValue\x129\n" +
	"\x18nested_oneof_int32_value\x182 \x01(\x05H\x01R\x15nestedOneofInt32Value\x12Y\n" +
	"\x16nested_oneof_value_one\x18. \x01(\v2\".grpc.runtime.testpb.Proto3MessageH\x01R\x13nestedOneofValueOne\x12N\n" +
	"\x14wrapper_double_value\x18\x11 \x01(\v2\x1c.google.protobuf.DoubleValueR\x12wrapperDoubleValue\x12K\n" +
	"\x13wrapper_float_value\x18\x12 \x01(\v2\x1b.google.protobuf.FloatValueR\x11wrapperFloatValue\x12K\n" +
	"\x13wrapper_int64_value\x18\x13 \x01(\v2\x1b.google.protobuf.Int64ValueR\x11wrapperInt64Value\x12K\n" +
	"\x13wrapper_int32_value\x18\x14 \x01(\v2\x1b.google.protobuf.Int32ValueR\x11wrapperInt32Value\x12O\n" +
	"\x15wrapper_u_int64_value\x18\x15 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x12wrapperUInt64Value\x12O\n" +
	"\x15wrapper_u_int32_value\x18\x16 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x12wrapperUInt32Value\x12H\n" +
	"\x12wrapper_bool_value\x18\x17 \x01(\v2\x1a.google.protobuf.BoolValueR\x10wrapperBoolValue\x12N\n" +
	"\x14wrapper_string_value\x18\x18 \x01(\v2\x1c.google.protobuf.StringValueR\x12wrapperStringValue\x12K\n" +
	"\x13wrapper_bytes_value\x18\x19 \x01(\v2\x1b.google.protobuf.BytesValueR\x11wrapperBytesValue\x12M\n" +
	"\tmap_value\x18\x1a \x03(\v20.grpc.runtime.testpb.Proto3Message.MapValueEntryR\bmapValue\x12P\n" +
	"\n" +
	"map_value2\x18\x1b \x03(\v21.grpc.runtime.testpb.Proto3Message.MapValue2EntryR\tmapValue2\x12P\n" +
	"\n" +
	"map_value3\x18\x1c \x03(\v21.grpc.runtime.testpb.Proto3Message.MapValue3EntryR\tmapValue3\x12P\n" +
	"\n" +
	"map_value4\x18\x1d \x03(\v21.grpc.runtime.testpb.Proto3Message.MapValue4EntryR\tmapValue4\x12P\n" +
	"\n" +
	"map_value5\x18\x1e \x03(\v21.grpc.runtime.testpb.Proto3Message.MapValue5EntryR\tmapValue5\x12P\n" +
	"\n" +
	"map_value6\x18\x1f \x03(\v21.grpc.runtime.testpb.Proto3Message.MapValue6EntryR\tmapValue6\x12P\n" +
	"\n" +
	"map_value7\x18  \x03(\v21.grpc.runtime.testpb.Proto3Message.MapValue7EntryR\tmapValue7\x12P\n" +
	"\n" +
	"map_value8\x18! \x03(\v21.grpc.runtime.testpb.Proto3Message.MapValue8EntryR\tmapValue8\x12P\n" +
	"\n" +
	"map_value9\x18\" \x03(\v21.grpc.runtime.testpb.Proto3Message.MapValue9EntryR\tmapValue9\x12S\n" +
	"\vmap_value10\x18# \x03(\v22.grpc.runtime.testpb.Proto3Message.MapValue10EntryR\n" +
	"mapValue10\x12S\n" +
	"\vmap_value12\x18% \x03(\v22.grpc.runtime.testpb.Proto3Message.MapValue12EntryR\n" +
	"mapValue12\x12S\n" +
	"\vmap_value14\x18' \x03(\v22.grpc.runtime.testpb.Proto3Message.MapValue14EntryR\n" +
	"mapValue14\x12S\n" +
	"\vmap_value15\x18( \x03(\v22.grpc.runtime.testpb.Proto3Message.MapValue15EntryR\n" +
	"mapValue15\x12S\n" +
	"\vmap_value16\x18- \x03(\v22.grpc.runtime.testpb.Proto3Message.MapValue16EntryR\n" +
	"mapValue16\x12D\n" +
	"\x12struct_value_value\x18/ \x01(\v2\x16.google.protobuf.ValueR\x10structValueValue\x12:\n" +
	"\fstruct_value\x180 \x01(\v2\x17.google.protobuf.StructR\vstructValue\x1a;\n" +
	"\rMapValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eMapValue2Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a<\n" +
	"\x0eMapValue3Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eMapValue4Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a<\n" +
	"\x0eMapValue5Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eMapValue6Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1a<\n" +
	"\x0eMapValue7Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eMapValue8Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1a<\n" +
	"\x0eMapValue9Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fMapValue10Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a=\n" +
	"\x0fMapValue12Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a=\n" +
	"\x0fMapValue14Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a=\n" +
	"\x0fMapValue15Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a[\n" +
	"\x0fMapValue16Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x05value:\x028\x01B\r\n" +
	"\voneof_valueB\x14\n" +
	"\x12nested_oneof_valueB\x11\n" +
	"\x0f_optional_value* \n" +
	"\tEnumValue\x12\x05\n" +
	"\x01X\x10\x00\x12\x05\n" +
	"\x01Y\x10\x01\x12\x05\n" +
	"\x01Z\x10\x02B)Z'github.com/kamalyes/grpc-runtime/testpbb\x06proto3"

var (
	file_testpb_proto3_proto_rawDescOnce sync.Once
	file_testpb_proto3_proto_rawDescData []byte
)

func file_testpb_proto3_proto_rawDescGZIP() []byte {
	file_testpb_proto3_proto_rawDescOnce.Do(func() {
		file_testpb_proto3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_proto3_proto_rawDesc), len(file_testpb_proto3_proto_rawDesc)))
	})
	return file_testpb_proto3_proto_rawDescData
}

var file_testpb_proto3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testpb_proto3_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_testpb_proto3_proto_goTypes = []any{
	(EnumValue)(0),                 // 0: grpc.runtime.testpb.EnumValue
	(*Proto3Message)(nil),          // 1: grpc.runtime.testpb.Proto3Message
	nil,                            // 2: grpc.runtime.testpb.Proto3Message.MapValueEntry
	nil,                            // 3: grpc.runtime.testpb.Proto3Message.MapValue2Entry
	nil,                            // 4: grpc.runtime.testpb.Proto3Message.MapValue3Entry
	nil,                            // 5: grpc.runtime.testpb.Proto3Message.MapValue4Entry
	nil,                            // 6: grpc.runtime.testpb.Proto3Message.MapValue5Entry
	nil,                            // 7: grpc.runtime.testpb.Proto3Message.MapValue6Entry
	nil,                            // 8: grpc.runtime.testpb.Proto3Message.MapValue7Entry
	nil,                            // 9: grpc.runtime.testpb.Proto3Message.MapValue8Entry
	nil,                            // 10: grpc.runtime.testpb.Proto3Message.MapValue9Entry
	nil,                            // 11: grpc.runtime.testpb.Proto3Message.MapValue10Entry
	nil,                            // 12: grpc.runtime.testpb.Proto3Message.MapValue12Entry
	nil,                            // 13: grpc.runtime.testpb.Proto3Message.MapValue14Entry
	nil,                            // 14: grpc.runtime.testpb.Proto3Message.MapValue15Entry
	nil,                            // 15: grpc.runtime.testpb.Proto3Message.MapValue16Entry
	(*wrapperspb.UInt64Value)(nil), // 16: google.protobuf.UInt64Value
	(*timestamppb.Timestamp)(nil),  // 17: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 18: google.protobuf.Duration
	(*fieldmaskpb.FieldMask)(nil),  // 19: google.protobuf.FieldMask
	(*wrapperspb.DoubleValue)(nil), // 20: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),  // 21: google.protobuf.FloatValue
	(*wrapperspb.Int64Value)(nil),  // 22: google.protobuf.Int64Value
	(*wrapperspb.Int32Value)(nil),  // 23: google.protobuf.Int32Value
	(*wrapperspb.UInt32Value)(nil), // 24: google.protobuf.UInt32Value
	(*wrapperspb.BoolValue)(nil),   // 25: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 26: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 27: google.protobuf.BytesValue
	(*structpb.Value)(nil),         // 28: google.protobuf.Value
	(*structpb.Struct)(nil),        // 29: google.protobuf.Struct
}
var file_testpb_proto3_proto_depIdxs = []int32{
	1,  // 0: grpc.runtime.testpb.Proto3Message.nested:type_name -> grpc.runtime.testpb.Proto3Message
	16, // 1: grpc.runtime.testpb.Proto3Message.repeated_message:type_name -> google.protobuf.UInt64Value
	0,  // 2: grpc.runtime.testpb.Proto3Message.enum_value:type_name -> grpc.runtime.testpb.EnumValue
	0,  // 3: grpc.runtime.testpb.Proto3Message.repeated_enum:type_name -> grpc.runtime.testpb.EnumValue
	17, // 4: grpc.runtime.testpb.Proto3Message.timestamp_value:type_name -> google.protobuf.Timestamp
	18, // 5: grpc.runtime.testpb.Proto3Message.duration_value:type_name -> google.protobuf.Duration
	19, // 6: grpc.runtime.testpb.Proto3Message.fieldmask_value:type_name -> google.protobuf.FieldMask
	1,  // 7: grpc.runtime.testpb.Proto3Message.nested_oneof_value_one:type_name -> grpc.runtime.testpb.Proto3Message
	20, // 8: grpc.runtime.testpb.Proto3Message.wrapper_double_value:type_name -> google.protobuf.DoubleValue
	21, // 9: grpc.runtime.testpb.Proto3Message.wrapper_float_value:type_name -> google.protobuf.FloatValue
	22, // 10: grpc.runtime.testpb.Proto3Message.wrapper_int64_value:type_name -> google.protobuf.Int64Value
	23, // 11: grpc.runtime.testpb.Proto3Message.wrapper_int32_value:type_name -> google.protobuf.Int32Value
	16, // 12: grpc.runtime.testpb.Proto3Message.wrapper_u_int64_value:type_name -> google.protobuf.UInt64Value
	24, // 13: grpc.runtime.testpb.Proto3Message.wrapper_u_int32_value:type_name -> google.protobuf.UInt32Value
	25, // 14: grpc.runtime.testpb.Proto3Message.wrapper_bool_value:type_name -> google.protobuf.BoolValue
	26, // 15: grpc.runtime.testpb.Proto3Message.wrapper_string_value:type_name -> google.protobuf.StringValue
	27, // 16: grpc.runtime.testpb.Proto3Message.wrapper_bytes_value:type_name -> google.protobuf.BytesValue
	2,  // 17: grpc.runtime.testpb.Proto3Message.map_value:type_name -> grpc.runtime.testpb.Proto3Message.MapValueEntry
	3,  // 18: grpc.runtime.testpb.Proto3Message.map_value2:type_name -> grpc.runtime.testpb.Proto3Message.MapValue2Entry
	4,  // 19: grpc.runtime.testpb.Proto3Message.map_value3:type_name -> grpc.runtime.testpb.Proto3Message.MapValue3Entry
	5,  // 20: grpc.runtime.testpb.Proto3Message.map_value4:type_name -> grpc.runtime.testpb.Proto3Message.MapValue4Entry
	6,  // 21: grpc.runtime.testpb.Proto3Message.map_value5:type_name -> grpc.runtime.testpb.Proto3Message.MapValue5Entry
	7,  // 22: grpc.runtime.testpb.Proto3Message.map_value6:type_name -> grpc.runtime.testpb.Proto3Message.MapValue6Entry
	8,  // 23: grpc.runtime.testpb.Proto3Message.map_value7:type_name -> grpc.runtime.testpb.Proto3Message.MapValue7Entry
	9,  // 24: grpc.runtime.testpb.Proto3Message.map_value8:type_name -> grpc.runtime.testpb.Proto3Message.MapValue8Entry
	10, // 25: grpc.runtime.testpb.Proto3Message.map_value9:type_name -> grpc.runtime.testpb.Proto3Message.MapValue9Entry
	11, // 26: grpc.runtime.testpb.Proto3Message.map_value10:type_name -> grpc.runtime.testpb.Proto3Message.MapValue10Entry
	12, // 27: grpc.runtime.testpb.Proto3Message.map_value12:type_name -> grpc.runtime.testpb.Proto3Message.MapValue12Entry
	13, // 28: grpc.runtime.testpb.Proto3Message.map_value14:type_name -> grpc.runtime.testpb.Proto3Message.MapValue14Entry
	14, // 29: grpc.runtime.testpb.Proto3Message.map_value15:type_name -> grpc.runtime.testpb.Proto3Message.MapValue15Entry
	15, // 30: grpc.runtime.testpb.Proto3Message.map_value16:type_name -> grpc.runtime.testpb.Proto3Message.MapValue16Entry
	28, // 31: grpc.runtime.testpb.Proto3Message.struct_value_value:type_name -> google.protobuf.Value
	29, // 32: grpc.runtime.testpb.Proto3Message.struct_value:type_name -> google.protobuf.Struct
	16, // 33: grpc.runtime.testpb.Proto3Message.MapValue16Entry.value:type_name -> google.protobuf.UInt64Value
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_testpb_proto3_proto_init() }
func file_testpb_proto3_proto_init() {
	if File_testpb_proto3_proto != nil {
		return
	}
	file_testpb_proto3_proto_msgTypes[0].OneofWrappers = []any{
		(*Proto3Message_OneofBoolValue)(nil),
		(*Proto3Message_OneofStringValue)(nil),
		(*Proto3Message_NestedOneofInt32Value)(nil),
		(*Proto3Message_NestedOneofValueOne)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_proto3_proto_rawDesc), len(file_testpb_proto3_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testpb_proto3_proto_goTypes,
		DependencyIndexes: file_testpb_proto3_proto_depIdxs,
		EnumInfos:         file_testpb_proto3_proto_enumTypes,
		MessageInfos:      file_testpb_proto3_proto_msgTypes,
	}.Build()
	File_testpb_proto3_proto = out.File
	file_testpb_proto3_proto_goTypes = nil
	file_testpb_proto3_proto_depIdxs = nil
}
